### ISSUE TITLE
Are there plans to integrate a error check mechanism?

### ISSUE THREAD

**Issue by CHEF-KOCH** [jedisct1/dnscrypt-proxy#113]
The original project had a mechanism to check if the configuration file has some errors which means if you set a wrong parameter or value the output showed you which line the error appears while trying to start dnscrypt-proxy. 

It would be great if we get such an option/mechanism back into this project here which would avoid a lot of questions and of course it would help people to '_debug_'  their problems. My idea here would be that the e.g. blacklist files and configuration file get such checks, the output/check could be provided with a separate batch/shell script/file.

**Comment by jedisct1** [comment]
Hi!

There are already quite a lot of checks, but there could be more.

Probably a big missing one was the fact that unknown properties were silently ignored.

This has been fixed in 2f00ad5ff05b7bc36cf6613544170558cca180c7 . It doesn't display the exact line yet, but it should be enough to spot a typo or another common error in the config file.

And as soon as that change was made, it pointed out that the example config file was wrong, or actually inconsistent with what the parser expected. The parser expected the timeout as `timeout_ms` and the config file has just `timeout`. This has been fixed by the way (`timeout` everywhere).
