### ISSUE TITLE
Donations/Support

### ISSUE THREAD

**Issue by CHEF-KOCH** [jedisct1/dnscrypt-proxy#114]
Are there plans to include PayPal, Patreon, Bitcoin etc. donations into the Readme/Project? I'm asking because I would like to support the project and the status of this simple questions is right now unclear. I use DNSCrypt now since the beginning and I feel like I should at least spent a cup of coffee or two.

**Comment by jedisct1** [comment]
Really, the best thing to do in order to help and support the project would be to contribute code, documentation and help with the current issues tagged "help wanted".

Writing blog posts and howtos on other websites is great, but meanwhile, the official documentation of the project is nonexistent even though everybody can edit it :(

Help is also needed for the website, for maintaining the resolvers lists, etc.

**Comment by idanka** [comment]
Lol:) MyBlog post:

http://www.idstudio.tk/2018/01/28/dnscrypt-proxy-2-0-0/

**Comment by elmakong** [comment]
also, providing public dnscrypt server also great idea!

**Comment by jedisct1** [comment]
Yes, more servers are good, especially in Asia.
