### ISSUE TITLE
 libdcplugin_example_ldns_blocking plugin doesn't work on Windows

### ISSUE THREAD

**Issue by CNMan** [jedisct1/dnscrypt-proxy#149]
I downloaded v1.4.1,but notice is 1.4.0:)
https://cnlic.com/wp-content/uploads/2014/10/DNSCrypt02.png

**Comment by jedisct1** [comment]
Did you try with a recent version?

**Comment by jedisct1** [comment]
Seems to work for me (tested on 1.5.0).

**Comment by CNMan** [comment]
@jedisct1 

```
"E:\Program Files\DNSCrypt\bin\dnscrypt-proxy.exe" --local-address=127.0.0.1:9999 --resolver-name=OpenDNS --resolver-address=208.67.220.220:443 --provider-name=2.dnscrypt-cert.opendns.com --provider-key=B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79 --tcp-only --max-active-requests=1024 --plugin "e:\Program Files\DNSCrypt\plugins\libdcplugin_example_logging",dns.log  --plugin "e:\Program Files\DNSCrypt\plugins\libdcplugin_example_ldns_blocking.dll",--domains=blk-domains,--ips=blk-ips --loglevel=1024 --test=0
```

[ERROR] Unable to read [dnscrypt-resolvers.csv]

**Comment by jedisct1** [comment]
Hi,

Thanks for providing your command-line.

It has quite a few inconsistencies that are unrelated to plugins:

`--resolver-address`, `--provider-name` and `--provider-key` are only useful if you are running your own DNS server. Since this is apparently not the case, do not use these switches.

The maximum log level is `7` (which is only for debugging), so no need to go as high as `1024`.

On versions before 1.6.0, you had to provide the path to the CSV file containing the list of resolvers:
`--resolvers-list=<full path to the CSV file>`.
You seem to be using 1.5.0, but the `--resolvers-list` does not appear in your command-line, so you might have seen another error saying that the CSV file couldn't be loaded.

So, let's trim down your command-line (assuming 1.6.0; on earlier versions, you need to provide the full path to the plugins, and add the one the CSV file):

    E:\Program Files\DNSCrypt\bin\dnscrypt-proxy.exe
    --local-address=127.0.0.1:9999
    --resolver-name=cisco
    --tcp-only
    --max-active-requests=1024
    --plugin libdcplugin_example_logging.dll,dns.log
    --plugin libdcplugin_example_ldns_blocking.dll,--domains=c:\rules\blk-domains,--ips=c:\rules\blk-ips

Note that the list of blocked IP addresses and domain names has to be in files that:
1) exist
2) are referenced using a full path

**Comment by CNMan** [comment]
@jedisct1 thanks,works well after follow your instruction.
