### ISSUE TITLE
Possible new feature implementing --provider-cert-file

### ISSUE THREAD

**Issue by RobotGuy** [jedisct1/dnscrypt-proxy#173]
Is there any chance that a command line option (possibly --provider-cert-file=&lt;filename&gt;) to provide the certificate directly from a file could be added like the dnscrypt-wrapper? As the only DNS servers I have access to are either Windows or configured via a web interface I can't for the life of me get the certificate TXT record to work as nether of them will accept the binary data and there is no other way to provide it.

I'm aware that this wouldn't be as flexible for running a public instance, but would be useful if the number of clients was limited.

**Comment by jedisct1** [comment]
In order to add forward secrecy, a change that will happen really soon is that server certificates will be constantly rotated. In this context, loading the cert from a file is not going to work.

`dnscrypt-wrapper` can serve the records directly (no need to configured them in a public authoritative server), and `dnscrypt-proxy` tries to get the certificates from both the standard DNS port (53) and the dnscrypt port (usually 443). If standard DNS queries fail on these ports, authenticated queries on the same port are unlikely to work either.

**Comment by RobotGuy** [comment]
Sorry, I wasn't aware of this and was using unprivileged ports to test with. Using port 53 worked fine.
