### ISSUE TITLE
Please remove OpenNIC JP server

### ISSUE THREAD

**Issue by gparent** [jedisct1/dnscrypt-proxy#177]
Hi,

I am the owner of the OpenNIC JP ns2/ns3 server.

Due to the high instability of dnscrypt-wrapper, I will be taking my server down indefinitely until further notice.

I would like to respectfully ask you to remove the server from your lists.

Thanks,

**Comment by jedisct1** [comment]
Hi,

Sorry to hear that you are having issues with dnscrypt-wrapper.

Are you running the latest version?

If you can provide details about what happens when it stop working, please do! dnscrypt-wrapper's maintainer is very responsive.

Meanwhile, your server has been removed from the list as requested.
