### ISSUE TITLE
MAN  installation error

### ISSUE THREAD

**Issue by leandroong** [jedisct1/dnscrypt-proxy#178]
Compilation halted on man folder installation about files not existence. Something to do with dnscrypt-proxy.8 and hostip.8 non-existence.

**Comment by jedisct1** [comment]
Unless you are willing to contribute to the code, you should download a release instead of the unstable development tree.

Releases can be downloaded here: http://download.dnscrypt.org/dnscrypt-proxy/ or if you are in a country that blocks it, here: http://download.dnscrypt.ovh/dnscrypt-proxy/

Generating the man pages requires the [ronn](https://github.com/rtomayko/ronn) tool. But the releases tarballs already have them pregenerated.
