### ISSUE TITLE
Can the resolvers list with signify be signed with signify?

### ISSUE THREAD

**Issue by alterstep** [jedisct1/dnscrypt-proxy#221]
Verifying the signature of `dnscrypt-resolvers.csv` requires either GPG or DNSSEC.

Graphical clients could retrieve updates, but having to bundle GPG or requiring it as a dependency is something I would like to avoid, in favor of a lightweight signing application, namely signify.

**Comment by jedisct1** [comment]
signify is a great tool, but:
1) It doesn't work on Windows yet (not a showstopper, porting it is straightforward)
2) Comments/metadata are not signed.

It signs the content of a file, not the file itself.

If they have been signed with the same key, the binary data of the `rm` executable can be served as a file named `cp`, which the user is going to think it actually is the `cp` file.

Signed packages are usually immune to this, because they embed full file paths, package versions, comments and more.

But the resolvers list doesn't have any metadata. Not even a serial version.

If a malicious resolver sneaks in, and we removed it later in, the signature would not prevent downgrading the file to the malicious version.

I really wish signify could sign metadata (or at least the comment), so that the signatures can embed trusted dates, version numbers and descriptions.

So I'm a bit on the fence. Adding signify signatures wouldn't solve this problem (that GPG signatures don't solve either).

And CSV files are not really a good fit for adding metadata.

**Comment by jedisct1** [comment]
Mmmm... Signify seems to be fine with extra lines after the signature.
That can be used to sign `comment || content_signature`.

**Comment by jedisct1** [comment]
Trying to make everyone happy: https://github.com/jedisct1/minisign :)

**Comment by alterstep** [comment]
Another request: can you keep a copy of `dnscrypt-resolvers.csv` file on dnscrypt.org?
Github may not always be reachable, and users can be concerned about seeing background queries to Github.

**Comment by jedisct1** [comment]
Done: http://download.dnscrypt.org/dnscrypt-proxy/ or http://updates.dnscrypt.org/dnscrypt-proxy/
