### ISSUE TITLE
Is dnscrypt supposed to work without proxy?

### ISSUE THREAD

**Issue by elhanan** [jedisct1/dnscrypt-proxy#222]
Hi, I spent all day installing dnscrypt for Windows 8.1 and the unofficial GUI for it by Noxwizard. I'm still not sure how to install libsodium, but I got opendns.com/welcome to show an orange check mark. But after many failed attempts to do so with proxy settings set to 127.0.0.1:53 and even over port 443 which just showed Firefox error pages or long loading times that never resolved, the first time and the only times I'm able to get openddns.com/welcome to show orange check marks is when I turn off the proxy on Network Settings on Windows 8.1. Is it supposed to work without local proxying or are either the GUI or dnscrypt programs doing it in the background?

Let me know if you need more information. Thanks for the help.

**Comment by jedisct1** [comment]
Hi @elhanan ,

Noxwizard's UI was the first public DNSCrypt UI for Windows. It's still maintained and works well with current versions of the proxy. It's not "unofficial" and is one of the recommended [DNSCrypt](http://dnscrypt.org) UIs.

A HTTP proxy retrieves web pages, and then forwards the result to the client. DNS requests are thus sent by the proxy itself. This is great in order to reduce latency, especially on a radio network where DNS queries tend be slow.

But the client DNS settings are irrelevant in this context, except to resolve the proxy's IP. The DNS queries required to fetch the pages are never sent by the client, always by the proxy.

**Comment by elhanan** [comment]
Cool. Thank you @jedisct1 . I was just wondering because Dominus Temporis' tutorial "DNSCrypt on Windows" says to change a Windows Network and Sharing Center setting, "As indicated, you just need to change your DNS settings to 127.0.0.1 and you will be all set (for instructions on that, you can look at the original article)," and when I do that my web pages won't load.
