### ISSUE TITLE
Tor routing

### ISSUE THREAD

**Issue by dnscrop** [jedisct1/dnscrypt-proxy#229]
1. How can i use xxxxx.onion as a DNSCrypt server?
2. I want to use DNSCrypt server on "Windows". Possible?
3. How can I use xxxxx.onion's DNSCrypt service on windows?

Expected routing: Both side are Windows.

User--DNSCrypt--->Tor(localhost:9150)|======|Tor(?:?)---DNSCryptServer--->AcrylicDNS(Windows DNS Server)

**Comment by dnscrop** [comment]
I want to use my own DNS(Acrylic). Because I can't trust public resolvers which says "no-log".
That's why I want dnscrypt-server for windows, and Tor routing support on client.

**Comment by dnscrop** [comment]
https://github.com/jedisct1/dnscrypt-proxy/issues/92

how about adding:

--socks5=X.X.X.X:X

If specified, DNSCrypt will use it to resolve|connect to the server.

**Comment by jedisct1** [comment]
Hi,

It might compile and work with Cygwin, but I am not aware of a anyone running the server on Windows. Give it a spin!

`dnscrypt-proxy` can be forced to use TCP, so you can redirect these to a proxy to tunnel its connections to Tor.

Not sure what you mean by "xxxxx.onion's DNSCrypt service" though. `.onion` domains reference Tor services and do not use DNS at all.

But since you are on Windows, how about DNS-over-TLS ?
You may want to consider Unbound instead of DNSCrypt + Acrylic.

A local Unbound resolver can communicate with an upstream Unbound resolver over a TLS connection (once again, something you can redirect to Tor).
Instead of a proxy, you may want to use [dns2socks](http://unbound.net/pipermail/unbound-users/2012-November/002689.html).

**Comment by espress0** [comment]
I'm on Linux, but I also want this feature.

> how about DNS-over-TLS
It's easy than Tor routing. You can use "stone" to achieve that.
http://gcd.org/sengoku/stone/

However, I want dnscrypt-proxy to use SOCKS5 proxy.
My ISP doesn't give a global IP address(NAPT), so I can't set up a server using global IP address(which
is shared with other ISP users).

I want to connect to my own DNS server from outside, using Tor routing.

===== Network Image
Client --- dnscrypt-proxy(DP) --- Tor ===Evil ISPs=== Tor --- dnscrypt-server(DS) --- my DNS daemon

===== How to connect
Launch DP with "--socks-proxy" option. DP will use it to resolve DNS/relay packet.
dnscrypt-proxy.exe --local-addr...... -R "mydnsserver" -L (...) --socks-proxy=127.0.0.1:9150

Client to DP(127.0.0.1:5353): Hey! Resolve Github.Server.
DP to Tor: SOCKS Proxy, open a connection to xxxxxxxxxxxx.onion:53/tcp.
Tor--->Tor: Hidden Service Protocol. Connection Established.
Tor to DS: Relaying packet to DS.
DS: relaying request to my DNS daemon(127.0.0.1:5364/tcp)


====
Um... Is this a DS? Do you have a plan to upload this to Debian repository for better management?
(e.g., apt-get update dnscrypt-wrapper)

https://github.com/jedisct1/dnscrypt-wrapper

**Comment by jedisct1** [comment]
Hi Espress!

dnscrypt-wrapper is the DNSCrypt server proxy. The actual repository is https://github.com/Cofyc/dnscrypt-wrapper

It can be installed using Homebrew, but I don't think there are packages for Linux distributions yet. For some reason, they packaged the client but not the server.

What I am planning to do is work on Docker images with unbound + namecore + ncdns + dnscrypt-wrapper.

**Comment by jedisct1** [comment]
You can use Tor's transparent proxy feature to redirect connections to your DNS server to Tor.

But I am not going to add support for Tor to dnscrypt, sorry. Using it in my country doesn't make me feel comfortable.

**Comment by Opensourcecommunitydevelopment** [comment]
@jedisct1 I know why user dnscrop uses it. I personaly prefer Acrylic over unbound in this situation. Better acrylic=>unbound[0-10]=>tcp-upstreamresolver forwarding. Acrylic greatly improves responsiveness and latency if on high latency, mobile networtk, proxy, or laggy connection. Why this is censoring application features because of france country? Option isn´t a default. direct connect is. But there maybe people behind forced (ntlm)proxy/firewall whatever.
@itoffshore transparent routing aka transport nat is only support on linux!

Connect:
dnscrypt-proxy does not support socks5 yet. you would need to socksify it to tor manually. 
dnscrypt-proxy does not support  domain names in resolvers! so no onion address.
But tor can map its address. just put into torrc config file the following:
`MapAddress  113.20.6.2			gc2tzw6lbmeagrp3.onion

MapAddress  113.20.8.17		l65q62lf7wnfme7m.onion`

https://www.torproject.org/docs/tor-manual.html.en
> MapAddress address newaddress

https://sourceforge.net/projects/dns2socks/
