### ISSUE TITLE
[feature] add support for multiple resolvers (win 32)

### ISSUE THREAD

**Issue by atomGit** [jedisct1/dnscrypt-proxy#233]
please consider adding support for multiple (-R) resolvers - i find that several of the U.S. NSs often have interruptions in their service

**Comment by jedisct1** [comment]
Sorry, but this is unlikely to get implemented anytime soon.

This would require way too many changes to the current code base and would go beyond the scope of the proxy.

A workaround is to run multiple instances, but when run as a service on Windows, a single set of registry keys is being used, so this doesn't work either.
The ability to run multiple instances on Windows would be great. Beyond making it possible to use multiple resolvers, it would also make it possible to use different local IPs with different plugins.

Instead of having a key for each property, the idea is to move to a single key with all the command-line options.

That is how I initially tried to do it, but I couldn't get it to work. I have to give it another try. But to be honest, do not expect this is a near future, as dnscrypt is being developed on my spare time which is currently very limited.

**Comment by jedisct1** [comment]
Something coming soon is a Docker image, running dnscrypt clients to multiple private or public services, with a DNS cache doing local DNSSEC validation, prefetching, and preventing leaks from local queries.

It will automatically use the fastest working servers of a pool, so you don't have to worry about servers being temporarily inaccessible.

It will also allow to do queries over TCP only, including to retrieve the certificates (good news for Tor users) and without the current horrible hack that forces client to send queries twice or more.

A Docker image might not be what you were initially thinking about, but it will solve the problem of properly setting up the client proxy on all operating systems.
