### ISSUE TITLE
Host a file on dnscrypt.org

### ISSUE THREAD

**Issue by alterstep** [jedisct1/dnscrypt-proxy#235]
I am working on self-updates for my client, and I need to download the list of available versions. It's a very small file + a minisig signature. Can you put this file on dnscrypt,org?

**Comment by jedisct1** [comment]
Hi there,

As you probably know, a copy of the `dnscrypt-resolvers.csv` can be downloaded here: `http://updates.dnscrypt.org/dnscrypt-proxy/dnscrypt-resolvers.csv`.

A cron job mirrors it daily from github, along with the signature. It's safe to do so specifically because of the signature.

Can something similar be done for your files? Have these fixes at a fixed location in your Github repository, and then I can set up a job to mirror them? How frequently should that happen?

**Comment by jedisct1** [comment]
Done. Your `updates` directory is now mirrored to `http://download.dnscrypt.org/updates/dnscrypt-osx-client`.
