### ISSUE TITLE
A complement to a VPN?

### ISSUE THREAD

**Issue by ibenl365** [jedisct1/dnscrypt-proxy#240]
I use PIA VPN. Is there an advantage to using DNSCrypt as well?

**Comment by jedisct1** [comment]
If you are using your own DNSCrypt resolver, yes.

If the VPN provider you are using is also offering access to their own DNSCrypt resolvers, yes.

In other scenarios, no. You would just be giving a copy of your data to two companies/organizations/people instead of one. In addition, it would make things slower by having CDNs return IP addresses of servers that can be far away from the VPN exit IP.
Use the name servers provided by the VPN service.
