### ISSUE TITLE
Source query port.

### ISSUE THREAD

**Issue by azalio** [jedisct1/dnscrypt-proxy#251]
I launched two dnscrypt-wrapper for load balancing on the server. 
But dnscrypt-proxy uses the same port for sending messages. 
Therefore, all requests from the same host always get into the same instance dnscrypt-wrapper. Under highload dnscrypt-wrapper it creates a bottleneck. 
Could you send requests from different ports?

```shell
ps auxwwww | grep 19560
root     19560  0.0  0.0   6908   868 ?        SLs  00:38   0:00 dnscrypt-proxy -d --local-address=0.0.0.0:56 --resolver-address=127.0.0.1:443 --provider-name=2.dnscrypt-cert.[domain_name] --provider-key=[key]

lsof -i -n | grep 19560
dnscrypt- 19560   root    8u  IPv4 3766962      0t0  UDP *:56 
dnscrypt- 19560   root    9u  IPv4 3766963      0t0  UDP *:26885 
dnscrypt- 19560   root   10u  IPv4 3766964      0t0  TCP *:56 (LISTEN)

All udp request go from port 26885.

00:47:21.244142 00:00:00:00:00:00 > 00:00:00:00:00:00, ethertype IPv4 (0x0800), length 554: 127.0.0.1.26885 > 127.0.0.1.443: UDP, length 512
00:47:21.244741 00:00:00:00:00:00 > 00:00:00:00:00:00, ethertype IPv4 (0x0800), length 474: 127.0.0.1.443 > 127.0.0.1.26885: UDP, length 432
00:57:07.960532 00:00:00:00:00:00 > 00:00:00:00:00:00, ethertype IPv4 (0x0800), length 554: 127.0.0.1.26885 > 127.0.0.1.443: UDP, length 512
00:57:07.960900 00:00:00:00:00:00 > 00:00:00:00:00:00, ethertype IPv4 (0x0800), length 410: 127.0.0.1.443 > 127.0.0.1.26885: UDP, length 368

Ubuntu 14.04.1 LTS
3.13.0-61-generic

dnscrypt-proxy --version
dnscrypt-proxy 1.6.0

**Comment by jedisct1** [comment]
Hi,

The dnscrypt client indeed uses a single UDP socket in order to communicate with the server.

That can be changed. You can also use TCP in order to work around this.

However your situation is quite unusual (a single client exceeding the capacity of the server running on a multicore CPU), so I'd like to know more about your setup.

What platform is the server running? What is the query rate?
dnscrypt-proxy should actually require more CPU cycles than the server.
