### ISSUE TITLE
WIth DNSCrypt installed, DNS server addreses entered are removed when disconnecting

### ISSUE THREAD

**Issue by CosmicVoyager** [jedisct1/dnscrypt-proxy#254]
Greetings,

WIth DNSCrypt installed, DNS server addreses entered in Network preferences are lost when disconnecting. For example, by turning WiFi off. They are removed from /Library/Preferences/SystemConfiguration/preferences.plist. And, of course, are gone when WiFi is turned back on.

I have to keep reentering the DNS addresses when everytime I open my MacBook.

Please fix

**Comment by jedisct1** [comment]
Are you referring to [this project](https://github.com/alterstep/dnscrypt-osxclient) ?

If this is the case, there is a field in the "Advanced" tab of the preference pane that says "When not using DNSCrypt, use the following static DNS servers:".

This is where you can enter a list of static DNS resolvers if you manage them manually instead of using DHCP.
