### ISSUE TITLE
Use with Unbound and OS X

### ISSUE THREAD

**Issue by faxotherapy** [jedisct1/dnscrypt-proxy#265]
Hello,
I have combined Unbound with dnscrypt-proxy. The couple works well for a certain time (typically half to one day), then DNS requests drop out. I have to relaunch the whole startup process again to make it work until DNS requests drop out again. Here are the commands I use once a day to make the couple Unbound + dnscrypt-proxy works again:
`` sudo launchctl unload /Library/LaunchDaemons/homebrew.mxcl.dnscrypt-proxy.plist && sudo launchctl unload /Library/LaunchDaemons/homebrew.mxcl.unbound.plist &&  sudo launchctl   load /Library/LaunchDaemons/homebrew.mxcl.dnscrypt-proxy.plist && sudo launchctl   load /Library/LaunchDaemons/homebrew.mxcl.unbound.plist``

Unbound receives on 127.0.0.1 and port 53, then forward to 127.0.0.1@40.

In dnscrypt-proxy .plist file, I have this:
      <string>/usr/local/opt/dnscrypt-proxy/sbin/dnscrypt-proxy</string>
      <string>--user=_dnscrypt</string>
      <string>--local-address=127.0.0.1:40</string>
      <string>--daemonize</string>
      <string>--ephemeral-keys</string>
      <string>--resolvers-list=/usr/local/etc/dnscrypt-resolvers.csv</string>
      <string>--resolver-name=dnscrypt.eu-nl</string>
      <string>--logfile=/private/var/log/dnscrypt.log</string>
      <string>--loglevel=7</string>

I use a VPN as well. I don't know if it's a problem. VPN port is UDP 1194.

Any idea to solve this issue so I no longer need to perform the whole startup process once a day?

Thanks very much in advance for your help.

**Comment by jedisct1** [comment]
When you don't get any DNS responses any more, can you check whether the issue come from Unbound or from dnscrypt-proxy?

You can try by sending a query specifically to port 40.

VPN clients also tend to override the DNS settings in order to force usage of the resolvers provided by the service. And they do it in many different ways, including adding local firewall rules.

That said, if you are using a VPN service, using dnscrypt is usually not a good idea. Your VPN service is already tunnelling everything including your DNS queries. Sending your DNS queries elsewhere can only slow down your connection and decrease your privacy.

**Comment by faxotherapy** [comment]
Hi jedisct1. Thanks for your prompt answer. I'm meditating on your post and will get back to this page if I find it necessary. Good day to you!
