### ISSUE TITLE
PPA for linux users

### ISSUE THREAD

**Issue by Krysisx** [jedisct1/dnscrypt-proxy#270]
Hi,

I want to install dnscrypt-proxy from ppa to keep it always up to date.
What PPA can I use?
I found:
- https://launchpad.net/~anton+/+archive/ubuntu/dnscrypt
- https://launchpad.net/~xuzhen666/+archive/ubuntu/dnscrypt

Thanks for your great work

**Comment by jedisct1** [comment]
Hi,

I've been successfully using https://launchpad.net/~anton+/+archive/ubuntu/dnscrypt but both look good, up to date and pretty similar.

They both share the same limitations, though:
- The resolvers list is not up to date, so you may want to update your copy from https://download.dnscrypt.org/dnscrypt-proxy/
- For some reason, support for plugins is not included.

**Comment by Krysisx** [comment]
great thanks, I updated the dnscrypt-proxy.csv list.
Now the best way to update my default dns resolver is to run: `dnscrypt-proxy --resolver-address=<ip>[:port]`
right?
Thanks

**Comment by jedisct1** [comment]
Without the package, the way to run it is `dnscrypt-proxy --resolver-name=<resolver name>` (or just `-R <resolver name>`)

But the Ubuntu package installs it with a configuration file in `/etc/default/dnscrypt-proxy`, and (for more recent Ubuntu version) with a systemd service `dnscrypt-proxy.service` that you can also edit.

This package is neat because it can use two resolvers at the same time for redundancy.

Pick resolvers close to your location, but that also matches the features you want. For example if you rely on SSHFP records to secure your ssh keys, use resolvers that support DNSSEC.

**Comment by Krysisx** [comment]
Ok thanks.

I ran: `sudo dnscrypt-proxy -R d0wn-al-ns1` but now it's stuck on `[NOTICE] Proxying from 127.0.0.1:53 to 31.171.155.107:54`

**Comment by jedisct1** [comment]
Check that it works well, and then add `-d` to the command the keep it running as a background process

**Comment by Krysisx** [comment]
Ok thanks, anyway I have created a script to test the best DNS in terms of speed.
Do you think it is ok to use `dig google.com @$ADDRESS -p $PORT` to test DNS response time and find the best?

Thanks
