### ISSUE TITLE
WSAECONNRESET 

### ISSUE THREAD

**Issue by TigerTrader** [jedisct1/dnscrypt-proxy#280]
The issue of WSAECONNRESET  is ongoing and there are dozens of other forums discussing the issue, but no resolution to the problem.

I can successfully connect to all the servers in the resolvers .csv list but all of them generate this error after some time:
[NOTICE] Proxying from 127.0.0.1:53 to 103.25.202.192:443
[WARNING] recvfrom(client): [Connection reset by peer [WSAECONNRESET ]]

I have tried opening ports 53 and 443 as well as disabling the firewall completely but this did not help.
It appears that every time a web page runs a script or a flash item then this error message is generated. It is unclear as to weather the connection is actually re-established and I have no idea if my dns queries are still encrypted after this error is generated.

I am running Win 10 (but same issue on Win 7) using dnscrypt 1.60 and the latest dnscrypt-proxy

I am simultaneously using Private Internet Access through OpenVPN. If I disconnect the VPN after setting up a dnscrypt connection and then reconnect the VPN the error is much less frequent, but nevertheless, it is still generated on some web sites! Shutting down the VPN does not stop the error message in DNSCrypt.

Does anyone have a working solution to this problem?

**Comment by jedisct1** [comment]
Don't use DNSCrypt with a VPN. It's usually doing more harm than good.
Your VPN is already authenticating and encrypting your DNS queries.
And PIA is one of the (surprisingly) rare VPN service operating their own DNS resolvers.

The error you are seeing means that a local app sent a DNS query and then refused the response. Maybe just because you closed a browser tab. It can be safely ignored.
As long as the only DNS resolver configured on your system is the proxy's address, you are using it.
