### ISSUE TITLE
No page access with DNScrypt on Win 7 & Antergos

### ISSUE THREAD

**Issue by macacohack** [jedisct1/dnscrypt-proxy#283]
Hi I have installed DNScrypt on both OS. But neither of them works when I set the DNS server on IPv4 to 127.0.0.1.

For Windows: I have followed all the steps and I got the confirmations that it was working properly. Connected to dnscrypt.eu-nl and for a while it did work.

Then I couldn't access pages anymore. I just got stuck after I type the domainname (firefox). And mentions unable to access the page.

So I reinstalled and again got all confirmations it was okay and for some reason it worked again after 2 or 3 times repeating this. But now it fails once again and I don't understand what's wronng. Is the server dnscrypt-eu.nl down or did I make an error somewhere?

I have the same with Antergos. Here I managed to install the package and have it running, get all the confirmations as well it's working. And it did work for a (short) while. Here the same as with Win 7, it doesn't work anymore as well. It seems to coincide.

The only way I can get my browser back working is by removing the 127.0.0.1 line and on both OS'es and set to automatic DNS. Now I can browse again. But I am not using DNScrypt anymore,. am I? 

Can someone give me some advice on how to determine where the problem lies and// or how to solve this?

**Comment by jedisct1** [comment]
Hi,

You can run the proxy in foreground mode, with --loglevel=7 in order to get some logs displayed.

Also make sure that your system clock is correct, as certificates are short-lived and really need a clock that isn't way off to be verified.

Also try different servers. `dnscrypt-eu.nl` seems to work fine from my networks, but as dnscrypt is getting some traction, it may start getting blocked by ISPs (the China's Great Firewall has blocked dnscrypt.org for a while).
