### ISSUE TITLE
RESOLVER_NAME for OpenDNS Family Shield?

### ISSUE THREAD

**Issue by c-gabri** [jedisct1/dnscrypt-proxy#296]
Hello there. I'm having trouble using OpenDNS because my ISP (Vodafone) forces me to use its own DNS addresses. On my PC I have solved the problem using DNSCrypt (thanks!).
I'd like to do the same on my (rooted) Android device and I'm trying to follow the procedure described here: https://dnscrypt.org/#dnscrypt-android. I'm supposed to edit a variable called RESOLVER_NAME, whose current value is "dnscrypt.org-fr".
If I want to use OpenDNS Family Shield (addresses 208.67.222.123 and 208.67.220.123) what should I put instead of that value? (I have asked this question to OpenDNS itself, but they sent me here).
And once I've installed DNSCrypt on Android, what should I do if I wanted to use different addresses in the future?
Thanks for your assistance

**Comment by jedisct1** [comment]
Hi,

The list of public resolvers is available here: https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv
And the first column is the resolver name to use.

In order to use Cisco FamilyShield, the name should be `cisco-familyshield`.

And in order to use a different resolver in the future, you just need to edit `RESOLVER_NAME` in `system/etc/init.d/99dnscrypt` and restart your phone.

**Comment by c-gabri** [comment]
Thanks for the very clear answer. Hope I'll manage to make it work.
