### ISSUE TITLE
(DNS leak test) shows (dnscrypt proxy server), but also the isp's dns

### ISSUE THREAD

**Issue by Leon8200** [jedisct1/dnscrypt-proxy#353]
I'm runing linux peppermint 6, I ran the DNS leaktest a few times and even rebooted a few times and can't figure out why the isp's dns shows up, I'm guessing dnscrypt is not working?

77.66.84.233 	resolver2.dnscrypt.eu 	NetGroup A/S 	Denmark
69.241.48.204 	rich-cns03-eth0-2.cran.ric1.comcast.net 	Comcast Cable 	United States
69.241.49.21 	rich-cns04-eth1.cran.ric1.comcast.net 	Comcast Cable 	United States
69.241.49.19 	rich-cns02-eth1.cran.ric1.comcast.net 	Comcast Cable 	United States
69.241.49.22 	rich-cns05-eth1.cran.ric1.comcast.net 	Comcast Cable 	United States
69.241.49.18 	rich-cns01-eth1.cran.ric1.comcast.net 	Comcast Cable 	United States
69.241.49.23 	rich-cns06-eth1.cran.ric1.comcast.net 	Comcast Cable 	United States
_______________________________________________________________________________

I installed dnscrypt-proxy using this ppa (repository ppa:anton+/dnscrypt)
and I have the DNS settings set to (127.0.0.1)
I just can't figureout why I am seeing the isp's DNS is something wrong ?

**Comment by AnOldNoob** [comment]
Hello Leon8200:
I don't know if you're still looking for resolution on this issue, but I installed my dnscrypt exactly the same way on Mint 17.3 and had exactly the same problem:

First, make sure your network IPv4 'method' shows "Automatic (DHCP) Addresses Only".
Second, change your DNS server to: 127.0.0.2 instead of 127.0.0.1. Evidently it has something to do with the anton+ ppa version.

This worked for me, hope it helps.
