### ISSUE TITLE
Files signed with different GPG key

### ISSUE THREAD

**Issue by Geblaat** [jedisct1/dnscrypt-proxy#376]
I was looking for the GPG key to verify the files, I found two other issues about it here, but the key posted there(1024D/1CDEA439) isn't used anymore.
It would also be nice if you could post the key details(preferably full fingerprint instead of key id) in multiple places for verification(for example, Github and Twitter.)

**Comment by jedisct1** [comment]
Files can be verified using a simple [DNS query](https://github.com/jedisct1/dnscrypt-proxy#download-and-integrity-check).

The `.sig` files are signatures made with the same key as the resolvers list, but it was indeed not mentioned in the documentation. This has been added both to the `README.md` file and to the website.

PGP signatures have become redundant and will be deleted, since Minisign is required to verify the CSV file anyway.

Thanks!
