### ISSUE TITLE
Android version does not use --ephemeral-keys

### ISSUE THREAD

**Issue by rugk** [jedisct1/dnscrypt-proxy#392]
When looking into the init.d script of the current ANdroid version I noticed it does not use `--ephemeral-keys`.

Should not it be using this option?

**Comment by jedisct1** [comment]
`--ephemeral-keys` has a cost. Which is negligible on a recent Intel CPU, but not so much on a phone.
Of course, it can be added, but I don't think it should be the default.

**Comment by rugk** [comment]
What about at least stating this in the guide?

I also encountered another issue, which could be mentioned in the guide: If you use AFWall+ you should enable network access for `root` - otherwise dnscrypt obviously fails to connect to any dns server you specify.

**Comment by jedisct1** [comment]
Unfortunately I don't have any Android devices.

I do my best to ensure that the proxy compiles with the Android toolchain, but I don't know much about Android, and I have no idea about what AFWall+ is.

So, pull requests from Android users in order to improve the code or the guide are more than welcome!

**Comment by rugk** [comment]
Okay, I'll have a look...

**Comment by licaon-kter** [comment]
`root` process does all the DNS requests hence that need.

**Comment by jedisct1** [comment]
The fact that ephemeral keys have a cost has been emphasized.
