### ISSUE TITLE
Script to Enable/Disable DNSCrypt on OSX

### ISSUE THREAD

**Issue by nlucchesi** [jedisct1/dnscrypt-proxy#431]
Is there a command line equivalent to the "Enable DNSCrypt" and "Disable DNSCrypt" MenuBar item?

I'd like to write a script to disable DNSCrypt when using Tunnelblick to establish a VPN connection using OpenVPN (and enable DNSCrypt when Tunnelblick disconnects).  The general idea is posted in the topic "Force DNS Setting While DNSCrypt is Enabled?" on the Tunnelblick forum:

https://groups.google.com/forum/#!forum/tunnelblick-discuss

A suggested approach is clear the DNS service of the active device using something like this:

`networksetup -setdnsservers $networkService ""`

Another suggested approach is:

https://support.opendns.com/entries/25477860

Can you recommend a way to script enabling/disabling DNSCrypt on OSX? 

Thank you.

- nello

**Comment by jedisct1** [comment]
Looks like this is more of a question about the [dnscrypt OSX Client](https://github.com/alterstep/dnscrypt-osxclient), but might know the answer anyway :)

In order to enable it, create a file (it can be empty - the content is ignored) named `/Library/Application Support/DNSCrypt/control/dnscrypt`.

In order to disable it, delete the file.

If you look at the OSX Client scripts in `/Library/PreferencePanes/DNSCrypt.prefPane/Contents/Resources/usr/scripts`, this is exactly what the `switch-to-dnscrypt.sh` and `switch-to-dhcp.sh` scripts do.

**Comment by nlucchesi** [comment]
Yes, you are correct: the question is about the OSX client.

Thank you for your suggestion.
