### ISSUE TITLE
second dnscrypt service

### ISSUE THREAD

**Issue by alex3026** [jedisct1/dnscrypt-proxy#451]
Is it possible to install dnscrypt as a second service but with 127.0.0.2 local address? will the two conflict each other? if possible, what would be the command to enter?

**Comment by licaon-kter** [comment]
What's the setup need ?

**Comment by alex3026** [comment]
to have two dnscrypt resolver-one primary and second for reserve in local area connection, because the one I use sometimes not working.

**Comment by jedisct1** [comment]
Hi Alex,

Sure. This is what `--local-address` switch is for:

```sh
dnscrypt-proxy --local-address=127.0.0.2 --resolver-name=...
```

**Comment by licaon-kter** [comment]
Or use a different port. Also, put both behind unbound so you don't care if one is down.

**Comment by alex3026** [comment]
**jedisct1**
I installed with the command you you say and everything looks installed correctly but is there a way to check if reserve dns is working? because dnsleak test only shows primary dns and I don't use wireshark.
also, if I want to change now the second resolver, how to do that without uninstalling the service because I'm not sure now if I enter "dnscrypt-proxy --uninstall" command, which service it will remove-only one of them or both?!

**licaon-kter**
I'm not familiar with cmd scripting so it's hard to me to enter correct command with different port using.

**Comment by licaon-kter** [comment]
first `dnscrypt... --local-address=127.0.0.1:40`
second `dnscrypt... --local-address=127.0.0.1:41`

You're on Windows?

**Comment by alex3026** [comment]
yes, on windows.

**Comment by jedisct1** [comment]
Ha :(

Unfortunately, on Windows, you are out of luck.

Although this will be improved in future versions, only one service can currently be installed.

**Comment by bitbeans** [comment]
See #418 :)

**Comment by alex3026** [comment]
I tried to do with 2 ports with the same service as **licaon-kter** suggested but got following error because of twice installing
![capture](https://cloud.githubusercontent.com/assets/15731901/17966686/d19b54ea-6ad3-11e6-9d0e-b5fb1b653c18.PNG)
then tried command "dnscrypt-proxy --local-address=127.0.0.1 --resolver-name=dnscrypt.org-fr --local-address=127.0.0.1:54 --plugin libdcplugin_example_ldns_aaaa_blocking.la"  but this just changed the port from 53 to 54 and after restarting I lost internet. 
I see there is no simple way to me to have two resolvers on windows; just one question **jedisct1**, is this correct command to block ipv6 queries while installing: "dnscrypt-proxy --install -R <name> --plugin libdcplugin_example_ldns_aaaa_blocking.la" ??

**Comment by jedisct1** [comment]
Yes, this is the correct way to enable that plugin.

**Comment by licaon-kter** [comment]
@alex3026 you can only have one resolver on port 53, but that one can be actually a forwarder to other ports where dnscrypt services listen, eg. unbound on Linux

Not sure how you'll do that on Windows yet as @bitbeans pointed out.

**Comment by alex3026** [comment]
I'll leave one resolver as main and use xiala or something else on a reserve. unbound and such programs seems a bit complicated to me. Anyway, thanks all for helping me.

**Comment by Opensourcecommunitydevelopment** [comment]
@alex3026 you use cmd back in 2016? :D
@licaon-kter  You CAN have two resolver running on same port, defaults to port 53. If bound to different localadresses! This Enables primary and secondary os dns server setting.

.\dnscrypt-proxy.exe --resolver-name=dnscrypt.org-fr --local-address=127.0.0.53
.\dnscrypt-proxy.exe --resolver-name=dnscrypt.org-fr --local-address=127.0.0.54

But here i have one question. i Use ipv6. And here i only see to have [::1]:53 once. Or someone can lead me to the quivalent of 127.0.0.1==::1 for 127.0.0.2 !=::2 (notavailable)
Is there only one loopback ipv6 adress? :( i use [::1]:54 successfully. i also recomment you to use unbound.

@bitbeans works same on windows ;) alex just failed installing second dnscrypt service, because the service name is hardcoded to be the same. --install arg can only be run once. workaround is to rename the already installed service and run command again with second resolver configured.

**Comment by licaon-kter** [comment]
So if port 53 is down Windows will use port 54? https://technet.microsoft.com/en-us/library/dd197515%28v=ws.10%29.aspx
If you have those and use the _Extended test_ on https://dnsleaktest.com/ you will see both servers, right?
