### ISSUE TITLE
[resolvers list] the list is not up to date

### ISSUE THREAD

**Issue by shibumi** [jedisct1/dnscrypt-proxy#467]
Hello,
The list seems no up to date. I get the following fingerprint for dnscrypt.eu-nl with my dnscrypt-proxy:

```
72DF:BE14:531F:F2AD:FD0F:BC8B:F711:B93D:799F:E4D0:34EC:D26B:8BF9:FFA9:32E7:2B79
```

But the official website says and your cve list says:

```
67C0:0F2C:21C5:5481:45DD:7CB4:6A27:1AF2:EB96:9931:40A3:09B6:2B8D:1653:1185:9C66
```

**Comment by jedisct1** [comment]
Hi,

You are confusing the public key with the certificate fingerprint.

The public key is used to verify the certificates. This is what the CSV file contains, and it is a long-term key, signing many certificates.

The fingerprint identifies the certificate that the client and the server agreed to use. A certificate is only valid for a short period of time -- in order to provide some forward security, the specification recommends a 24 hours TTL. So, the fingerprint changes every 24 hours as well.

It's mostly a diagnostic tool for servers operators. It's not present in any configuration files, since it's constantly changing.
