### ISSUE TITLE
Suggestion TCP persistent keep-alive long term connection query multiplexing remove RTT/overhead

### ISSUE THREAD

**Issue by Opensourcecommunitydevelopment** [jedisct1/dnscrypt-proxy#474]
actually --tcp-only is what it says since version 1.7.0! this is just great. 
The latency of establishing connections in tcp for every single request could be dropped RTT alot if using keep-alive connections. push multiple querys async in parralell over a single connection per resolver. less overhead. resolver server would free up connections and client too.
Will this feature or can it be added in future with current protocol?
in high latency mobile network it would make huge difference. or for prefered resolver in other side of world.
may could TFO TCP-FAST-OPEN improve this further

**Comment by jedisct1** [comment]
TCP Fast Open is already being used since version 1.5.0.

TCP connections have intentionally to be closed with this version of the protocol.
TCP support on Cisco resolvers is broken, and resolvers are not generally not prepared for keeping many open TCP connections. Although this might change now that we DNS-over-TLS has been introduced.

DNS-over-TLS and DNS-over-HTTP2 are actually a better fit than DNSCrypt for TCP. But TCP remains a poor choice for a typical DNS workload.
