### ISSUE TITLE
If DNS is encrypting, how is my ISP sending me cease pirating warnings?

### ISSUE THREAD

**Issue by Replicant1769** [jedisct1/dnscrypt-proxy#475]
Even running through VPN. Shouldn't DNScrypt encrypt my activity data stream back to provider?

Hope this is a suitable place to ask. Thanks

**Comment by licaon-kter** [comment]
Yes it does, but only DNS requests, those are not even used when you connect to other peers say in a torrent, since those are direct IP connections.

Eg, you want to conntect to myfavouritepiratesite dot com (pictures of pirate hats that is):
* request is encrypted to DNS -> ISP sees only a DNS request, not what site you asked for
* you PC gets the site IP
* your PC connects to that IP -> ISP sees IP
* ISP has IP is does a reverse DNS and sees that IP used for myfavouritepiratesite dot com

Now, if torrents are involved, usually when an ISP send you warnings it's because they got that info from another entity, one that was usually getting the torrent and taking notes of IPs that seed/peer, again that has nothing to do with DNS.

/mark as invalid and close

**Comment by Replicant1769** [comment]
Thank you so much for your response.

cheers

**Comment by Replicant1769** [comment]
"your PC connects to that IP -> ISP sees IP"

What stops this? Is this still the case when you're using a third-party DNS server that is not your ISP's?
OR routing internet traffic through a VPN?

**Comment by licaon-kter** [comment]
VPN yen, it will always see the VPN IP.
