### ISSUE TITLE
Can't start dnscrypt-proxy on OSX, port 53 used by mDNSresponder

### ISSUE THREAD

**Issue by td0** [jedisct1/dnscrypt-proxy#477]
So, dnscrypt-proxy always failing to start after booting my mac. I ran `lsof -i :53` to check process which is using port 53. mDNSresponder using it (tcp *:53, udp *:53)

I did a very dirty hack to get dnscrypt-proxy running. Kill mDNSresponder process, and quickly start dnscrypt-proxy daemon before mDNSresponder kicked-off (yeah, it runs automatically after being killed).
Ofc I've tried to listen to another port on dnscrypt-proxy command, but it didn't seem to work. It's like every time I run my browser/anything which needs DNS, will request to port 53, while dnscrypt is listening to another port. I can't put a custom port on mac DNS configuration. (or can I?). That's very annoying.
I've also tried alterstep's dnscrypt OSX client. It worked just fine, broken on the next day. It simply switch the dnscrypt back and forth, like it's trying to connect but failed every time. I assume the same port conflict happens.

As for now, I can only think of making a function in .bash_profile to kill mDNSresponder and start dnscrypt-proxy immediately. Is there any better way?

**Comment by jedisct1** [comment]
That's weird.

Since when is mDNSresponder *listening* to port 53?

I never saw it listen to that port. Did you had to start some service in order to get there?

Killing a system daemon doesn't sound like a good idea no matter what.

**Comment by td0** [comment]
Ikr, that was very dirty hack.
I don't know. Before I found out that *:53 occupied by mDNSresponder, I've restarted my mac several times and run dnscrypt before anything else just in case. And it just failed.

Even now, the mDNSresponder is still using *:53 on ipv6.
![image](https://cloud.githubusercontent.com/assets/4467386/19019717/d5f79ec2-88ba-11e6-9438-9d35136c7bd5.png)

I saw many issues regarding dnscrypt-proxy failed to run on OSX, I wonder if most of them are caused by mDNSresponder? 😕

**Comment by jedisct1** [comment]
`mDNSResponder` listens to port 53 when applications using the native hypervisor run. Typically, software such as Veertu and Docker for Mac.

This is quite annoying, because at the same time, OSX doesn't allow specifying a specific port for DNS queries. And `mDNSResponder`'s DNS proxy listens to all IPs, effectively preventing another local resolver or proxy from running.

`mDNSResponder`'s DNS proxy can be disabled in its configuration file: `/System/Library/LaunchDaemons/com.apple.mDNSResponder.plist`

Change
```
                <key>com.apple.mDNSResponder.dnsproxy</key>
                <true/>
```

to

```
                <key>com.apple.mDNSResponder.dnsproxy</key>
                <false/>
```

But that file being in `/System`, changing it requires [disabling SIP](http://apple.stackexchange.com/questions/208478/how-do-i-disable-system-integrity-protection-sip-aka-rootless-on-os-x-10-11).

The only possible workaround I can think of is to listen to a different port, and use a local firewall rule to redirect port `53` to it. The whole thing is getting overly complicated 👎

**Comment by jedisct1** [comment]
Unfortunately, this is not really a bug in `dnscrypt-proxy`, and something that the app can work around.

**Comment by jedisct1** [comment]
Try to have the proxy listen to a different port, such as `5300`, and add the following firewall rules:

```sh
(echo "rdr pass on lo0 inet proto udp to port 53 -> 127.0.0.1 port 5300" ; echo "rdr pass on lo0 inet proto tcp to port 53 -> 127.0.0.1 port 5300" ) | sudo pfctl -ef -
```

It should do the trick.

**Comment by td0** [comment]
Googled `mdnsresponder`, found no any helpful information on that. Yeah, I run Docker for Mac. So that's why..
As for now, I unload `mdnsresponder` daemon by executing:
`launchctl unload /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist`
I think I'm gonna try your solution instead, since it doesn't mess around with system daemon. Thanks
