### ISSUE TITLE
One resolver seems failed to work on Android

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [jedisct1/dnscrypt-proxy#479]
I found a resolver seems does not work on Android when I used [Kernel Adiutor](https://play.google.com/store/apps/details?id=com.grarak.kerneladiutor) to run 99dnscrypt script. I have already installed BusyBox via [BusyBox Free](https://play.google.com/store/apps/details?id=stericson.busybox).

Test 1:
![screenshot_2016-10-03-21-12-32](https://cloud.githubusercontent.com/assets/10364351/19038982/a9139eaa-89b0-11e6-854a-123e548ecd55.png)

Test 2 (replace the second resolver as cisco):
![screenshot_2016-10-03-21-18-27](https://cloud.githubusercontent.com/assets/10364351/19039032/f37d757e-89b0-11e6-988b-d31a92697460.png)

Test 3 (second resolver is recovered, replace the first resolver as cisco):
![screenshot_2016-10-03-21-37-24](https://cloud.githubusercontent.com/assets/10364351/19039531/f7831c30-89b2-11e6-8943-3de2d7963157.png)

**Comment by jedisct1** [comment]
Hi,

Sorry to hear that one of the resolvers doesn't seem to work.

What resolver appears not to be working?

**Comment by KrasnayaPloshchad** [comment]
To my eyes, dnscrypt.org-fr should work as what test 3 performanced.

**Comment by jedisct1** [comment]
I'm sorry, but I don't understand what I should be looking at, at where `dnscrypt.org-fr` is on these pictures.

Is your question about what "The certificate is not valid for the given safety margin" message means?

**Comment by KrasnayaPloshchad** [comment]
Yes, I fell concern this would cause `dnscrypt.org-fr` works not proper.

**Comment by jedisct1** [comment]
Hi,

This message is nothing to worry about. It is only useful as a diagnostic tool for people running their own resolvers.

As long as at least one certificate is currently valid, everything is going to work.

The third example is actually a very bad one, as it is using a single, long-term certificate, providing very little forward secrecy.

The protocol recommends changing the certificate every 24 hour.

In order to rotate certificates without interrupting the service, servers send multiple certificates that overlap. Some can not be valid any more, some can be not valid yet, but this is fine, as long as one is valid.
