### ISSUE TITLE
1.7.0 on ubuntu with systemd doenst read socket file alternative listen address

### ISSUE THREAD

**Issue by xternaal** [jedisct1/dnscrypt-proxy#501]
Hi,
Maybe I am doing something wrong, but on ubuntu 16.04 I setup dnscrypt (have installed many times on other systems).
However when using systemd i edit **dnscrypt-proxy.service** to include username and resolver to use and
I then edit **dnscrypt-proxy.socket** file to use 192.168.1.10:53 as I want a windows DNS server to use it as the forwarder.

When running **systemctl status dnscrypt-proxy.socket** the socket is running as expected on 192.168.1.10:53

But... dnscrypt-proxy.service is still using 127.0.0.1:53 and can only be accessed from the local machine. 

> systemd[1]: Started DNSCrypt client proxy.
> dnscrypt-proxy[30414]: [INFO] + DNS Security Extensions are supported
> dnscrypt-proxy[30414]: [INFO] + Provider supposedly doesn't keep logs
> dnscrypt-proxy[30414]: [NOTICE] Starting dnscrypt-proxy 1.7.0
> dnscrypt-proxy[30414]: [INFO] Generating a new session key pair
> dnscrypt-proxy[30414]: [INFO] Done
> dnscrypt-proxy[30414]: [INFO] Server certificate with serial '0001' received
> dnscrypt-proxy[30414]: [INFO] This certificate is valid
> dnscrypt-proxy[30414]: [INFO] Chosen certificate #808464433 is valid from [2016-06-26] to [2017-06-26]
> dnscrypt-proxy[30414]: [INFO] Server key fingerprint is 3730:AAB4:B7FD:40F6:3C42:B12C:60DF:B615:8392:B6AF:9AA4:4CFD:C282:0BAC:E68E:2624
> dnscrypt-proxy[30414]: [NOTICE] Proxying from 127.0.0.1:53 to 113.20.8.17:443

Weird because there is no dnscrypt-proxy.socket for 127.0.0.1:53?? (I dont know enough about how systemd works...)

Anyway, if I add the line **--local-address=192.168.1.10:53** to **dnscrypt-proxy.service** it runs fine (so long as I change the **dnscrypt-proxy.socket** back to **127.0.0.1:53**, otherwise it fails with [Address already in use])

> 
> ExecStart=/usr/local/sbin/dnscrypt-proxy \
>           --resolver-name=d0wn-nl-ns3 \
>           --user=dnscrypt \
>           --local-address=192.168.1.10:53

So it would seem dnscrypt is not using the .socket file properly under systemd in ubuntu 16.04?

**Comment by jedisct1** [comment]
Looks like `dnscrypt-proxy` was not compiled with systemd support

 So, systemd starts it, but the dnscrypt-proxy socket is not handled by systemd. Which is totally fine.

Where does the package you installed come from?

**Comment by CrisBRM** [comment]
@jedisct1 On that note, I am using a systemd system for the first time and both of my services and sockets are 'inactive (dead)'.

```
λ desktop ~ → systemctl status dnscrypt-proxy.socket
● dnscrypt-proxy.socket - dnscrypt-proxy listening socket
   Loaded: loaded (/etc/systemd/system/dnscrypt-proxy.socket; enabled; vendor preset: enabled)
   Active: inactive (dead)
   Listen: 127.0.0.2:53 (Stream)
           127.0.0.2:53 (Datagram)
λ desktop ~ → systemctl status dnscrypt-proxy.service
● dnscrypt-proxy.service - DNSCrypt client proxy
   Loaded: loaded (/etc/systemd/system/dnscrypt-proxy.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:dnscrypt-proxy(8)
```

**Comment by jedisct1** [comment]
Instructions on how to change the socket address with systemd have been added to the wiki.

**Comment by bvh4f00** [comment]
Hi @jedisct1, I seem to have the same problem as xternaal.

I installed the dnscrypt-proxy in my raspi, i followed the guide from http://www.dornochplace.com/2017/05/18/use-for-a-raspberry-pi-dnscrypt-and-pihole/, because i want to run 2 dnsproxy just in case one of them is down. 
Just a note. I didn't install pihole. my aim is just to make the dnscrypt works  at this point.

I created the dnscrypt-proxy@.service template and socket exactly like in the guide. but everytime I reboot the raspi they conflict with dnsmasq, making it failed to start. I did set the ListenStream and ListenDatagram to 127.10.10.1:40 and 127.10.20.1:40, respectively. But when i check journalctl to see why my fnsmasq failed to start, both dnscrypt-proxy keep using address 127.0.0.1:43. I don't know why dnsproxy won't use the address I specify as in the systemd socket files.

These are the screenshot of my service and socket file:

![selection_041](https://user-images.githubusercontent.com/33506757/32589188-ae80dc0a-c545-11e7-978e-7970974bb256.png)

![selection_042](https://user-images.githubusercontent.com/33506757/32589192-b6199b0a-c545-11e7-9733-272bf6286771.png)




Journactl output:

`-- The start-up result is done.
Nov 09 00:34:55 raspberrypi polkitd(authority=local)[653]: Registered Authentication Agent for unix-session:c2 (system bus name :1.12 [lxpolkit], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Nov 09 00:34:55 raspberrypi dnscrypt-proxy[410]: Thu Nov  9 00:34:55 2017 [INFO] Server certificate with serial #1510136236 received
Nov 09 00:34:55 raspberrypi dnscrypt-proxy[410]: Thu Nov  9 00:34:55 2017 [INFO] This certificate is valid
Nov 09 00:34:55 raspberrypi dnscrypt-proxy[410]: Thu Nov  9 00:34:55 2017 [INFO] Server certificate with serial #1510136236 received
Nov 09 00:34:55 raspberrypi dnscrypt-proxy[410]: Thu Nov  9 00:34:55 2017 [INFO] This certificate is valid
Nov 09 00:34:55 raspberrypi dnscrypt-proxy[410]: Thu Nov  9 00:34:55 2017 [INFO] Favoring version #131072 over version #65536
Nov 09 00:34:55 raspberrypi dnscrypt-proxy[410]: Thu Nov  9 00:34:55 2017 [INFO] Chosen certificate #1510136236 is valid from [2017-11-08] to [2017-11-09]
Nov 09 00:34:55 raspberrypi dnscrypt-proxy[410]: Thu Nov  9 00:34:55 2017 [INFO] Using version 2.0 of the DNSCrypt protocol
Nov 09 00:34:55 raspberrypi dnscrypt-proxy[410]: Thu Nov  9 00:34:55 2017 [INFO] Server key fingerprint is 5480:077A:6C88:23B0:8F2C:009F:C572:32D1:72F7:A53F:8016:862E:0A2A:5055:05AA:353B
Nov 09 00:34:55 raspberrypi dnscrypt-proxy[410]: Thu Nov  9 00:34:55 2017 [NOTICE] Proxying from 127.0.0.1:53 to 212.47.228.136:443
Nov 09 00:34:55 raspberrypi dnscrypt-proxy[408]: Thu Nov  9 00:34:55 2017 [INFO] Server certificate with serial '0001' received
Nov 09 00:34:55 raspberrypi dnscrypt-proxy[408]: Thu Nov  9 00:34:55 2017 [INFO] This certificate is valid
Nov 09 00:34:55 raspberrypi dnscrypt-proxy[408]: Thu Nov  9 00:34:55 2017 [INFO] Chosen certificate #808464433 is valid from [2017-09-11] to [2018-09-11]
Nov 09 00:34:55 raspberrypi dnscrypt-proxy[408]: Thu Nov  9 00:34:55 2017 [INFO] The key rotation period for this server may exceed the recommended value. This is bad for forward secrecy.
Nov 09 00:34:55 raspberrypi dnscrypt-proxy[408]: Thu Nov  9 00:34:55 2017 [INFO] Server key fingerprint is D616:D268:09D2:29A7:9457:DE07:3DE8:EBD8:3C24:BFF3:2BF7:B406:108B:44DA:51FE:3711
Nov 09 00:34:55 raspberrypi dnscrypt-proxy[408]: Thu Nov  9 00:34:55 2017 [NOTICE] Proxying from 127.0.0.1:53 to 77.66.84.233:443
`


Can you please tell me what's wrong? I want to make it work. thanks.

**Comment by jedisct1** [comment]
Don't use systemd sockets. Unless you're a systemd expert, it always causes issues.
You can also use the pre-built binaries here https://github.com/jedisct1/dnscrypt-proxy-installer

**Comment by bvh4f00** [comment]
I use the prebuilt binary from https://github.com/jedisct1/dnscrypt-proxy-installer.

I see.. what should I do then? Do i hardcode the ip address directly in the service unit files?

**Comment by jedisct1** [comment]
All the parameters are read from the configuration file, including the local IP address and port to listen to.
