### ISSUE TITLE
Questions regarding dnscrypt-proxy 1.8.0

### ISSUE THREAD

**Issue by zymase** [jedisct1/dnscrypt-proxy#512]
I'm not a geek yet I've used _dnscrypt-proxy_ and continue to use it with the front-end application _Simple DNSCrypt_. I had switched from "manual" (command-line) use of _dnscrypt-proxy_ to _Simple DNSCrypt_ mainly because of the ease of integration of domain and IP _blacklists_.

I discover that latest _dnscrypt-proxy 1.8.0_ includes a configuration file, _**dnscrypt-proxy.conf**_, which should make it a breeze to personalize _dnscrypt-proxy_ and would allow me to abandon the heavy (nevertheless worthy) _Simple DNSCrypt_.

I'd appreciate to understand a few points which may be obvious but which are unclear in my mind:

**1- What do /tmp/ , /var/log/ , /etc/ correspond to as mentioned in the dnscrypt-proxy.conf file?**
```
QueryLogFile /tmp/dns-queries.log
LogFile /var/log/dnscrypt-proxy.log
BlackList domains:/etc/dnscrypt-blacklist-domains.txt
```
**2- Using dnscrypt-proxy.conf (once edited of course)**

_Start DNSCrypt-proxy with a given resolver :_

Before : `dnscrypt-proxy.exe -R dnscrypt.org-fr --install`
Now : `dnscrypt-proxy.exe dnscrypt-proxy.conf`?

_Test a given resolver :_

`dnscrypt-proxy.exe -R dnscrypt.org-fr --test=0` as before?

_Stop DNSCrypt-proxy :_

`dnscrypt-proxy.exe --uninstall` as before?

**3- Modifying the dnscrypt-proxy.conf and/or modifying a blacklist (domains/IPs) :**
Is stopping DNSCrypt-proxy required? That would be :
1- STOP DNSCrypt-proxy, 2- EDIT dnscrypt-proxy.conf and/or blackliste, 3- START DNSCrypt-proxy

Thanks for your help :)

**Comment by jedisct1** [comment]
`/tmp`, `/var/log`, etc. are directories, so what follows these options if the full path to a file.

On Windows, you may want to use something like `/Users/micro/Desktop/dns-query.log` instead.

Command-line switches still work as they used to. So, the easiest way to quickly check whether server certificates are valid remains:
`dnscrypt-proxy.exe -R dnscrypt.org-fr --test=0`

Alternatively, start the proxy without actually installing the service:
`dnscrypt-proxy.exe dnscrypt-proxy.conf`

If everything works as expected, install the service:
`dnscrypt-proxy.exe --install-with-config-file=dnscrypt-proxy.conf`

In order to uninstall:
`dnscrypt-proxy.exe --uninstall` as before.

This is briefly [documented here](https://github.com/jedisct1/dnscrypt-proxy/blob/master/README-WINDOWS.markdown#advanced-configuration).

If changes are made to a blacklist, the service indeed has to be restarted after having made the changes. This might be improved in future releases.

Hope it helps!
