### ISSUE TITLE
Auto update dnscrypt-resolvers.csv 

### ISSUE THREAD

**Issue by sam1275** [jedisct1/dnscrypt-proxy#516]
This resolver list seems changing rather quick, so I think it should be auto updated.
And it may be good if the software can auto switch to another resolver in case one of the current using resolver is not present in the latest list. And this function could be switched off if someone is very care about security, to prevent using a unwanted resolver.

**Comment by jedisct1** [comment]
Hi Sam,

The package already includes a script to [update the CSV file](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-update-resolvers.sh.in).

What to do when the configuration is invalid is really up to the user, or the GUIs. From the server perspective, the safest/least surprising behavior is to exit with an error instead of silently making a decision that may not match what the user wants.
