### ISSUE TITLE
ServiceName being ignored in conf.

### ISSUE THREAD

**Issue by Nurple** [jedisct1/dnscrypt-proxy#524]
Heya,

ServiceName in the config file is being ignored, I had to use --service-name= for it it take.

This is on both Win7 and Win10 with v1.8.1.

**Comment by bezdupel** [comment]
I have exactly the same problem too.

**Comment by jedisct1** [comment]
Sounds like a dumb question from a generic support service, but: what sequence of operation did you do? What was the expected result? What happened instead?

The path to the configuration file is stored in the registry. So the service name is only being used when the service is installed (and that has been clarified in the sample configuration file since).

**Comment by Nurple** [comment]
I just it again on a clean VM, I ran;

C:\Program Files\DNSCrypt-Proxy>DNSCrypt-Proxy --install-with-config-file="C:\ProgramData\DNSCrypt\DNSCrypt-Primary-Resolver.conf

which has a ServiceName set, yet I get the default dnscrypt-proxy as the service name.

**Comment by jedisct1** [comment]
I see. There is a chicken-and-egg problem here.

And given the fact that `ServiceName` is not never used by the service itself, but only for installing it, it's probably better to completely remove it from the config file. That has been done in 68ff8eb5990d99db2744941752195e74d108b918 .

I'm going to update the documentation to suggest add `--service-name` to the command line instead.
