### ISSUE TITLE
Configuration file/args co-existence

### ISSUE THREAD

**Issue by untitledxi** [jedisct1/dnscrypt-proxy#536]
Hi, after setting up an instance with the configuration file i noticed a bit of an annoying issue with the current system -- it doesn't allow people to override configuration by providing command line args.

It would be nice if a user can have a generic configuration file and do something like:

```
dnscrypt-proxy --conf=/etc/dnscrypt-proxy.conf --local-address=0.0.0.0:53
```

which would fetch the configuration file and simply override all the settings specified in the command line.

In its current form, specifying anything after the configuration file, would force the proxy to ignore the configuration file completely.

Granted this may as well be a very niche feature-request, it may allow for a more "script-friendly" proxy environment.

**Comment by jedisct1** [comment]
I'm not a big fan of having two concurrent ways of configuring something that can be used simultaneously.
"Damn, I configured this resolver name, and I know it works, but I can't connect". "Ahh, the startup script has a command line to override the server port number; that was initially a test for another resolver, I forgot about it".

When using systemd, having the socket information in one place, and the rest of the information (including socket information, but that is ignored, in that case) is already confusing.

But what exactly happens when you specify something that's already defined? Especially with plugins: does the command-line deletes and replaces the whole list of plugins defined in the file? 

Are these added to the one from the file? So how do you change one? How do you delete one? Since the order they are loaded is important, how do you change the order?

For all these reasons, I'd really prefer the configuration to be all in one place. Either in a config file or in the command-line, but not a mix of both.

**Comment by untitledxi** [comment]
Thank for the follow-up, seems like a very good reason to keep them separated.
