### ISSUE TITLE
generate-domains-blacklist.py task will stop when HTTP error

### ISSUE THREAD

**Issue by CNMan** [jedisct1/dnscrypt-proxy#555]
```
root@localhost:~/dnscrypt-proxy/contrib# python generate-domains-blacklist.py > dnscrypt-blacklist-domains.txt
Loading data from [file:domains-whitelist.txt]
Loading data from [file:domains-blacklist-local-additions.txt]
Loading data from [http://osint.bambenekconsulting.com/feeds/c2-dommasterlist.txt]
Loading data from [http://hosts-file.net/.%5Cad_servers.txt]
[http://hosts-file.net/.%5Cad_servers.txt] could not be loaded: HTTP Error 503: Service Unavailable
root@localhost:~/dnscrypt-proxy/contrib#
```

**Comment by jedisct1** [comment]
Hi,

This is the intended behavior. It stops and returns an error, instead of creating an incomplete list.

You usually want to store the output of the command to a temporary file, and only replace the file if no errors were returned:

```sh
generate-domains-blacklist.py > list.tmp && mv -f list.tmp list
```

So, if a server is temporarily unavailable, the current list is not changed. A list that is slightly out of date is usually better than a list where many entries are missing because of a temporary outage of a server.
