### ISSUE TITLE
unavailable loggin path cuase startup failure for the service [Plugin]

### ISSUE THREAD

**Issue by ZIEXED** [jedisct1/dnscrypt-proxy#560]
Service fails to start if logging plugin enabled and the drive where logs are saved is unavailable
The drive where dns logs are saved take a few seconds every startup to be available
it would be great if u can change the behavior to not save any dns queries if the drive is unreachable

**Comment by jedisct1** [comment]
Hi,

Generally, if the configuration is invalid, we want to abort as soon as possible instead of starting the service in a partial state that may not match what you expect.

If the root cause is that the service starts before a specific drive is mounted, this may be solved by enabling delayed start on the service. See http://www.thewindowsclub.com/delay-loading-of-specific-services-windows

That's a bit of an ugly hack, and a script actually checking the availability of the drive would be cleaner, but the former workaround may be good enough.
