### ISSUE TITLE
Android device without sleep

### ISSUE THREAD

**Issue by avently** [jedisct1/dnscrypt-proxy#590]
Hello.
I use AOSP 7.1.1 and it looks like dnscrypt-proxy do not allow device sleep for many hours. For example, my phone can use 1% of battery per 3-4 hours of deep sleep. When I installed dnscrypt this time stays around 30-60 minutes. So dnscrypt use ~10% every night. Of course I checked my theory before writing this issue. 
I installed dnscrypt. Many hours without sleep. -10%. 
I "killall dnscrypt" and fixed iptables. -3% for equal time period. 

I could not find any information related to wakelocks and this issue in dumpsys batterystats. So i do not know what info i can give you. 
Before this new nougat rom I had 5.1. And I hadn't any problems. 
P..S. I use armv8 version compiled by myself without any changes.

**Comment by licaon-kter** [comment]
Not sure Doze can handle root apps.

**Comment by rmenessec** [comment]
I recommend either [Greenify](https://play.google.com/store/apps/details?id=com.oasisfeng.greenify) or [Purify](https://play.google.com/store/apps/details?id=com.kingstudio.purify). I personally use Greenify. Note that Greenify **can** use the Xposed framework, but no longer relies as heavily on Xposed as it once did.

[Amplify](https://play.google.com/store/apps/details?id=com.ryansteckler.nlpunbounce) requires Xposed and hasn't been updated in a while, but it allows you to exercise fine-grained control over wakelocks, alarms, and so forth. It can be combined with Greenify, and I believe it can be combined with Purify.

Having one of these tools or a similar tool installed is essentially required to obtain the best possible battery life, whether or not you're using dnscrypt-proxy.

**Comment by avently** [comment]
@rmenessec
Are you really think this method is a good alternative to making changes to source code?
And of course this method will not work I think. 

Maybe developer can answer us about what does he think

**Comment by rmenessec** [comment]
@avently , I'm not sure what you mean by "not work". If you mean that a doze-mode manager might cause dnscrypt-proxy to stop functioning temporarily... yes, that's possible. If that happens, either whitelist dnscrypt-proxy or simply uninstall the manager. You have nothing to lose but a few minutes of your time.

If using one of the managers I mentioned does not help or temporarily impairs dnscrypt-proxy, there's also [DNS Manager](https://play.google.com/store/apps/details?id=com.okirat.dnsmanager), which uses the dnscrypt-proxy code, and may have a solution or work-around for the issue you're experiencing.

It doesn't bother me whether or not you use one of my suggestions. I was merely attempting to be helpful, since I see you've waited a few weeks for a response. Your response to me comes across as rude and dismissive.

**Comment by avently** [comment]
@rmenessec I'll try your suggestions. I mean the developer may know the best way to do what we need. This is temporary solution and external apps needed. That's why it's not good. 
As I already mentioned on Android 5.1 Dnscrypt works fine. So why not to fix it in Android 7.1?

**Comment by rmenessec** [comment]
@avently Greenify works best with Xposed, but does not require it. It doesn't require root, either, but I believe some features will be unavailable without it.

I realize that the lack of Xposed will likely prevent you from using Amplify, yes; I wasn't sure if anything had changed [since February](https://www.xda-developers.com/rovo89-updates-on-the-situation-regarding-xposed-for-nougat/).

I haven't tried Purify, but it doesn't mention root or Xposed requirements. Then again, it doesn't really describe how it works; Greenify may be the optimal choice, here. Well, that, or DNS Manager, depending on whether that has doze issues. DNS Manager or something similar may be a good idea in any case, in order to ensure that your DNS settings aren't overridden when you switch from one network to another. [Override DNS](https://play.google.com/store/apps/details?id=net.mx17.overridedns) can also do this, but doesn't include DNSCrypt support that I'm aware of.

I believe there are a couple of other doze-mode managers out there, but I haven't looked in a few months, and I don't recall what the requirements were.

It's possible that dnscrypt-proxy simply must **always** be running, short of integrating DNSCrypt support directly into Android; if it's not running, DNS requests can't be proxied through it. If your device is dozing and a network request involving DNS is triggered, dnscrypt-proxy would have to run at least briefly in order to proxy the request.

**Comment by licaon-kter** [comment]
I did [this](https://github.com/smarek/android-unbound-dns/issues/18) a while ago, caveats mentioned aside it works ok most of the time.

**Comment by avently** [comment]
@licaon-kter do you have the device that sleeps good on Android Nougat with your apk?

**Comment by licaon-kter** [comment]
Forgot to test on N, just LL and MM. Feel free to test and report back :+1: :)

**Comment by avently** [comment]
@rmenessec
Greenify doesn't work. I tested several nights.

**Comment by rmenessec** [comment]
@avently I'm sorry to hear that. I just became aware of one other no-Xposed solution (or workaround, if you prefer) that might be worth testing: [Naptime](https://play.google.com/store/apps/details?id=com.franco.doze).

**Comment by avently** [comment]
@rmenessec already tried. Same result. Maybe in the next version of Android it will be fixed...

**Comment by rmenessec** [comment]
@avently Same result with DNS Manager instead of dnscrypt-proxy?

**Comment by avently** [comment]
As dnscrypt-proxy

**Comment by zin105** [comment]
https://i.imgur.com/5p0ofDl.png

Marked spot was my first night with DNScrypt. Looks to me like it was able to deep sleep fine since % didn't move.

**Comment by avently** [comment]
I updated Android many times since March. Now I don't see any problems with dnscrypt. So I'm closing the issue.
