### ISSUE TITLE
Errors on laptop

### ISSUE THREAD

**Issue by lopachecoc** [jedisct1/dnscrypt-proxy#594]
When I start my laptop, I do not have internet connection until I manually select a wifi network to connect to. This is by design.

dnscrypt-proxy keeps creating errors like this:
02/12/17 11:04:39 [INFO] Refetching server certificates
02/12/17 11:04:54 [ERROR] Unable to retrieve server certificates
02/12/17 11:05:18 [INFO] Refetching server certificates
02/12/17 11:05:33 [ERROR] Unable to retrieve server certificates
02/12/17 11:06:00 [INFO] Refetching server certificates
02/12/17 11:06:15 [ERROR] Unable to retrieve server certificates
02/12/17 11:06:45 [INFO] Refetching server certificates
02/12/17 11:07:00 [ERROR] Unable to retrieve server certificates
02/12/17 11:07:33 [INFO] Refetching server certificates
02/12/17 11:07:48 [ERROR] Unable to retrieve server certificates
02/12/17 11:08:24 [INFO] Refetching server certificates
02/12/17 11:08:39 [ERROR] Unable to retrieve server certificates
02/12/17 11:09:18 [INFO] Refetching server certificates
02/12/17 11:09:33 [ERROR] Unable to retrieve server certificates

Obviously it will not succeed until I connect to the internet. dnscrypt-proxy should not try to contact the dns server until internet connection is available.

The problem with this is that once I manually connect to the wifi network, dnscrypt-proxy does not seem to be able to fetch the server certificate. I have to restart the dnscrypt-proxy service, and then everything works.

All the testing was done with ResolverName dnscrypt.org-fr

System is Windows 7, 64bit.

dnscrypt-proxy 1.9.4

**Comment by jedisct1** [comment]
The proxy needs to download the certificate in order to start the service. This requires Internet connectivity. More generally, it doesn't really make sense to run it without the ability to reach the configured server.

The errors you get are expected. I think the time between retries increases and they keep failing. This is especially useful when bandwidth is metered, such as when using radio networks.

In your unusual setup, starting the proxy after the network connectivity is available is indeed the best thing to do. This can probably be scripted, but using a nice user interface such as Simple DNSCrypt will also makes this easy.

**Comment by lopachecoc** [comment]
Unfortunately it is a very common scenario.

You take your laptop to a random internet cafe, start the laptop, and before you have the chance to add the cafe's wifi network, dnscrypt-proxy gives up on trying to reach the dns server because no internet connectivity was available.
