### ISSUE TITLE
Filter ports for 'random' option

### ISSUE THREAD

**Issue by chew-z** [jedisct1/dnscrypt-proxy#597]
I have a suggestion for a minor improvement. 'Random' option in .conf file is great but my firewall restricts certain ports - so for example 53, 443, 5353 is kosher but 2053 is not.  As a result when I am using random I end up (at random) with not working DNS and I have to restart dnscrypt.

Perhaps it would be possible to add another option where one can specify allowed ports - like all, or 53 and 443 only and then dnscrypt-proxy would select at random only form this subset.

**Comment by elgab** [comment]
Why don't you further sanitize dnscrypt-resolvers.csv instead?
eg: keep only resolvers from your continent, desired ports.

**Comment by chew-z** [comment]
Of course I can do that. But perhaps this is common issue and @jedisct1 can add some simple filtering. Hence the feature suggestion.

**Comment by jpgpi250** [comment]
since the suggestion box seems to be open: I recently found this article, regarding the [14 eyes countries](https://www.my-private-network.co.uk/vpn-provider-14-eyes-country-something-know/). Maybe a choice could be given to avoid these countries

**Comment by jedisct1** [comment]
The purpose of the `random` option is to be able to ship a default configuration file that works out of the box.

Prior to that, packages had to either impose a default resolver to users, or users were forced to edit files before the proxy could be used.

Some people may want to restrict the list to resolvers that are close to them. Other people want to use specific ports. Other people want to filter specific countries.

For all these different use cases, filtering the `dnscrypt-resolvers.csv` file is probably the best way to go. You get all the flexibility one can get from shell scripts to do custom filtering.

**Comment by chew-z** [comment]
In case someone needs such simple filtering [here is a quick script](https://gist.github.com/2bfae0d48feed4dd3e342cb05e396d82)

**Comment by pysiak** [comment]
I recognize port 2053 as DNScrypt Poland which I run. Obstacles in reaching
this port has been signalled to me before and so I run the same service
also on port 443.

You may safely s/2053/443/ on the resolvers file, it's just I never asked
Frank to include 443.

On 28 Feb 2017 11:04, "Robert J." <notifications@github.com> wrote:

In case someone needs such simple filtering here is a quick script
<https://gist.github.com/2bfae0d48feed4dd3e342cb05e396d82>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jedisct1/dnscrypt-proxy/issues/597#issuecomment-282996490>,
or mute the thread
