### ISSUE TITLE
TCP or UDP

### ISSUE THREAD

**Issue by uihdff** [jedisct1/dnscrypt-proxy#602]
If DNSCrypt is running on a router, is there a performance or security difference in choosing to use UDP or TCP ?

**Comment by war59312** [comment]
In terms of technology difference (https://en.wikipedia.org/wiki/User_Datagram_Protocol#Comparison_of_UDP_and_TCP)...

UDP is almost always a little bit faster since you don't have the full error correction (checksum only) or the 3-way handshake like you do with TCP.

I'd argue TCP is then inherently more secure than TCP. But! Both depend on the security of the application(s) being used.

Anyone have any benchmark numbers to see speed advantages?

**Comment by uihdff** [comment]
war59312,

   Thanks for the reply.

   So there shouldn't be any noticeable lag using TCP versus UDP ?

**Comment by jedisct1** [comment]
Use UDP if possible.

TCP is neither more reliable nor more secure.

**Comment by uihdff** [comment]
Why should UDP be used instead of TCP ?

**Comment by war59312** [comment]
@uihdff I'd bet no real worthwhile difference, given the developer is recommending UDP.

I'd go with @jedisct1 recommendation.

Probably just a tad bit better performance. Again without numbers, it's only speculative.

Personally, I stay with TCP, but that's just me. I prefer it in cases where there are no real performance differences. But again, my advice is to go with the developer if you don't understand the technology at play.

**Comment by uihdff** [comment]
@war59312,

Thanks for the follow-up.
