### ISSUE TITLE
Stop working randomly 

### ISSUE THREAD

**Issue by davideaicardi** [jedisct1/dnscrypt-proxy#616]
Sometimes on macOS it stops working, and every services running can't connect, fix is change server or disable and enable again

**Comment by jedisct1** [comment]
Unfortunately, there is nothing I can do without more information.

**Comment by davideaicardi** [comment]
hmm. i'm sure that it did it even before the last update, if you need anything in particular to debug it i'll try to provide it

**Comment by jedisct1** [comment]
What does the configuration file look like?

**Comment by TraderStf** [comment]
FYI, there is bugs in Apple Network (DNS) syst pref (dialog).
- One is old since 2012, just delete (*) totally the config used and recreate a new Ethernet (or wifi...) from scratch. replace or edit or add does not make it!
- Another is, perhaps the same, that if you play to much with the dns settings in the prefs, it stops working.
- This can also be triggered when using third party VPN.

I know it's a bit unclear but for sure there are problems with how DNS are managed by macOS.
I have reported this several times, there is less in 10.12.3 but some are still there.
The only solution I have is that (*) delete.

**Comment by davideaicardi** [comment]
Thanks for your time !

**Comment by NHellFire** [comment]
Seeing this too (v1.9.4, Ubuntu 17.04).
For the last 6hrs, it wasn't responding to requests (all timed out) and I had to restart it to get it functional again.
I've set log level to debug, I'll see if there's anything helpful if it happens again.
