### ISSUE TITLE
Detecting errors with dnscrypt-proxy

### ISSUE THREAD

**Issue by uihdff** [jedisct1/dnscrypt-proxy#628]
Running Entware-NG version of dnscrypt-proxy 1.9.1 on an Asus RT-AC88U with Asuswrt-Merlin 380.65.

1) If dnscrypt-proxy is running on a router, what syslog entries should be monitored to determine if dnscrypt-proxy is encountering problems ?

2) After installation and configuration of dnscrypt-proxy, how can you tell if dnscrypt-proxy is running correctly ?

**Comment by jedisct1** [comment]
Messages are tagged with relevant severity levels, so instead of looking at specific patterns, you can just look at what is being logged from `dnscrypt-proxy` with `Warning` or `Error` levels.

The best way to check if your DNS queries are proxied by `dnscrypt-proxy` is to pause it:

`sudo pkill -STOP dnscrypt-proxy`

If everything's broken and you're not able to resolve any name, you were obviously using it :)

Then, resume its activity:

`sudo pkill -CONT dnscrypt-proxy`
