### ISSUE TITLE
dnscrypt-proxy author

### ISSUE THREAD

**Issue by uihdff** [jedisct1/dnscrypt-proxy#641]
@jedisct1,

Are you the original developer of dnscrypt-proxy or is this your port of the application ?

**Comment by jedisct1** [comment]
I designed the protocol and wrote a first client (MacOS-only, absolutely terrible), along with horrible patches for unbound and djbdns. That was essentially a weekend project.
I rewrote a more serious client later, which is `dnscrypt-proxy`, and shortly after having pushed the code to Github, I was pleasantly surprise to see that a nice person called Yecheng Fu had written a server proxy based on it.
Around the same time, someone (Noxwizard) wrote a Windows GUI for it, so since people were actually finding dnscrypt useful, I had no choice but keep working on it :)

**Comment by uihdff** [comment]
How did dnscrypt-proxy end up on OpenWrt and Entware-NG ?

**Comment by jedisct1** [comment]
Probably the same way as all other software packaged for any operating system or distribution. Someone packaged it.

As far as I can remember, the first router OS to ship it was Tomato Shibby (including great integration in the admin panel), so maybe the OpenWRT package is based on it.
