### ISSUE TITLE
Question about LocalAddress Port with a DNSCRYPT-V2-PROTOCOL resolver

### ISSUE THREAD

**Issue by zymase** [jedisct1/dnscrypt-proxy#665]
Running dnscrypt-proxy 1.9.5 on Windows 7.
No problem, only a possible optimization question.

I read on \doc\DNSCRYPT-V2-PROTOCOL.txt,

> The default port for this protocol should be 443, both for TCP and UDP.

I read on dnscrypt-resolvers.csv, concerning **dnscrypt.org-fr**,

> Properties / Version = 2

**Question 1**
Does the resolver's version mentioned in dnscrypt-resolvers.csv correspond to the PROTOCOL?

**Question 2**
If Answer to _Question 1_ is _Yes_,  then should I change my LocalAddress Port to 443?
```
ResolverName dnscrypt.org-fr
LocalAddress 127.0.0.1:53
Include d:\My Data\BLOCKERS\DNSCrypt\all-config.conf
```
Change _127.0.0.1:53_ TO _127.0.0.1:443_ ?

I'm not an expert so thanks for taking that into consideration should my two questions be totally insane!

**Comment by jedisct1** [comment]
`443` is the default port for communications between the proxy and the resolver.

Between clients and the proxy, you should stick to port `53` especially on Windows, that doesn't have any option to change the DNS port.

**Comment by zymase** [comment]
Merci Frank!
Since I opened this thread, considering the answer must have been most certainly useful for me only, I'll close the door walking backwards with a wide and grateful thanks! (A la royale, en somme!)

**Comment by jedisct1** [comment]
The version rather refers to a compatibility level. The initial protocol was not clearly specified and didn't include any protection against amplification attacks. No one is still using this except Cisco. But it doesn't cause any compatibility issues: recent clients can still talk to these servers.

There was then a specification, and additional mechanisms such as the one that requires questions to be as large as the responses. That's what virtually all the resolvers are implementing. Since clients can talk to both these resolvers and to cisco's, the compatibility "version" is the same even if the protocol is not exactly the same. It's compatible.

Another, incompatible encryption system, was specified, and later implemented. This requires both recent versions of the clients, and the latest code for the server. So, that's a different "compatibility version", even though the current dnscrypt-proxy code can handle both versions.

**Comment by zymase** [comment]
That is an in-depth explanation which brings a naive question (mine) to a pertinent development (yours), likely to find an echo within techies. My pleasure!

I do notice (a simple remark expecting no answer for myself) that in the dnscrypt-resolvers.csv file, dnscrypt.org-fr is the only resolver to be shown as being version=2. I do at least understand this is not related to my LocalAddress port. Pragmatism being often the credo of illiterates I'll stick on that basic philosophy for the time being (I'm afraid it'll last considering I have more years in back of me than in front!)

Thanks again, Frank.
