### ISSUE TITLE
DNSCrypt questions

### ISSUE THREAD

**Issue by Mikh-3** [jedisct1/dnscrypt-proxy#683]
Hi,
I have a question, I'm using OpenDNS on my router for my whole network and OpenDNS on my computer and when using DNSCrypt it disconnects my connection to OpenDNS.

My first question is, how can I use OpenDNS server's while still be connected to DNSCrypt because I want the content filtering.

My second question is does this only happen to my computer or anyone using the same adapter? Because it changed the IP on my LAN2.

OpenDNS only has a DNSCrypt server for IPV6, not IPV4, in case you were wondering.

**Comment by jedisct1** [comment]
The OpenDNS company doesn't exist any more. They have been bought by Cisco.

In order to share your Internet activity with Cisco, you can choose `cisco` in the list of public resolvers. This will work over IPv4.

But dnscrypt-proxy includes much more powerful filtering capabilities, that work with any servers:

https://github.com/jedisct1/dnscrypt-proxy/wiki/Filters
https://github.com/jedisct1/dnscrypt-proxy/wiki/Cloaking
https://github.com/jedisct1/dnscrypt-proxy/wiki/Forwarding
https://github.com/jedisct1/dnscrypt-proxy/wiki/Caching

**Comment by Mikh-3** [comment]
Oh alright, you listed them under Cisco, lol. OpenDNS still remains as a subsidiary, it's not been dissolved by Cisco.
