### ISSUE TITLE
Question regarding logging

### ISSUE THREAD

**Issue by Mikh-3** [jedisct1/dnscrypt-proxy#688]
When a server on the public list of servers says no logging is it refrained from actually keeping logs by the way of how DNSCrypt works through a built-in feature and said setting announces on the list, for instance, that the 'no log' setting is active.

**Comment by jedisct1** [comment]
The `no log` flag is just informative. Technically, nothing prevents a server advertised as logging from logging, because the DNS protocol is old and doesn't allow this using its current infrastructure.

The safest option is to run your own server (and this is very simple: https://github.com/jedisct1/dnscrypt-proxy/wiki/How-to-setup-your-own-DNSCrypt-server-in-less-than-10-minutes).
