### ISSUE TITLE
Dnscrypt through android tor

### ISSUE THREAD

**Issue by itspull** [jedisct1/dnscrypt-proxy#699]
Here's a link to a conversation about configuration for this, in the case there needs one to be present: https://www.wilderssecurity.com/threads/dnscrypt-through-tor.351495/

Having read the article, I'm still unsure of how to properly set android tor to use dnscrypt as an exit node. Aren't all exit nodes in tor hard-coded?

And yet, there is a response to use tcp-only option in dnscrypt and configure tor to have an exit node use dnscrypt.

So, it seems it is maybe possible, given theres a correct configuration in orbot.

The tor doc mentions a $fingerprint option for setting exit nodes.

How do I map a fingerprint string for the dnscrypt servers? Is this at all possible?

**Comment by jedisct1** [comment]
Are you running an *exit node*?

These usually requires servers and static IPs, so since you mentioned Android, this is unlikely.

If you are just running a client node, DNS queries for requests send over Tor are handled by Tor exit nodes, not by your device.

If you are actually running a Tor exit node, I don't really see the point of using DNSCrypt instead of a local resolver either.

**Comment by itspull** [comment]
@jedisct1 

> If you are just running a client node, DNS queries for requests send over Tor are handled by Tor exit nodes, not by your device.

hmm, interesting.

ok, i'd like to insert a question about this. excuse if maybe it's out of scope with this ticket, but i have to ask, since here there's an actual line of conversation open to maybe receive an absolute answer for this, or, perhaps, a pointing toward a right direction to trail for an answer.

i've understood that tor can handle dns requests. the how of that was beyond me cos i understood orbot only spoke in tcp, now i know that those requests are being made by exit nodes, outside of tor and then piped back?

uh, really?

so, if that's the default way tor works, there can't possibly be a way get dnscrypt and tor to work together with say, dnsmasq as a local dns resolver. it seems like any attempts to configure them along side one another will fail.

my question: is there a way to configure a local dns resolver to use both tor and dnscrypt? ex. dnscrypt for the dns lookups and tor for http/tls?

**Comment by jedisct1** [comment]
You can't have Tor use a local DNS server. You can still run a local DNSCrypt if you like; it will be used by applications that are not compatible with Tor.
But if your intent is to hide your IP address, these applications already have it since you're sending them data.

Don't make your life complicated for a half working solution. Just get a VPN.

**Comment by itspull** [comment]
> Don't make your life complicated for a half working solution. Just get a VPN.

fair enough. thanks.
