### ISSUE TITLE
error!!!! error again!!!!

### ISSUE THREAD

**Issue by Barbodos77** [jedisct1/dnscrypt-proxy#708]
Guys!!!! I do not understand you, with each update some kind of error which takes several hours to correct !!! Is it really hard to test before sending to production! Or update to update mang! again I didn’t have the privilege to listen to port 53, I’ve already tried everything and, as a result, removed your program, fucked up

**Comment by Yinchie** [comment]
User error much? Never had any problems here.
Don't know your configuration, I blame your own lack of knowledge :D

**Comment by jedisct1** [comment]
You didn't provide any details about your environment, or the actual error message.

But if you get an error saying that port 53 cannot be opened due to some privilege issue, it is likely that you didn't run the app as `root`, or from an elevated console.

See the [Installation](https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation) section of the documentation for guidance.
