### ISSUE TITLE
cannot run C compiled programs.

### ISSUE THREAD

**Issue by blub4747** [jedisct1/dnscrypt-proxy#717]
Hi guys,

Iam trying to built dnscrypt-proxy on my dietpi eg debain 8 system.

When I run ./configure I get the following error msg

If you meant to cross compile, use `--host'.
See `config.log' for more details

Which parts of my config.log should I therefore provide?

Ps. I if the issuse is related to libsodium. Iam using the latest version from the tar arviche.

**Comment by jedisct1** [comment]
Maybe you can just use already compiled binaries?

https://github.com/jedisct1/dnscrypt-proxy-installer

**Comment by blub4747** [comment]
Thx for the help. I will let it run and see if works fine.

**Comment by enilfodne** [comment]
Same error cropped up as well, when looking through `config.log` turned out that `gcc` couldn't find `libsodium.so`. Set a `LD_LIBRARY_PATH` env to include the directory where your `libsodium` resides.

**Comment by jedisct1** [comment]
@enilfodne I guess you compiled libsodium yourself (and didn't run `ldconfig` or read the `dnscrypt-proxy` documentation if you are using Fedora).

Just curious: why didn't you just install the package shipped with your distribution?

**Comment by enilfodne** [comment]
Both compiled from scratch.

It started as the official packages omitting the `ldns` extensions (blocking, logging etc.). Later turned out to be a faster way of updating the server `csv` list.

**Comment by jedisct1** [comment]
> Both compiled from scratch.

This is a terrible state of affairs.

Can you report this to the package maintainer, so that the packages get eventually fixed and people don't have to recompile things themselves?

The source code also includes the `dnscrypt-update-resolvers.sh` script to update the CSV list. It should be part of official packages as well.

**Comment by enilfodne** [comment]
I've checked the most recent builds (listed [here](https://admin.fedoraproject.org/pkgdb/package/rpms/dnscrypt-proxy/)) and it appears that neither `ldns` plugins nor `dnscrypt-update-resolvers.sh` are available in the package.

I think the plugins are missing because they add `ldns` as dependency, which might be too much for some use-cases. Not sure why there's  no `cron` or `systemd` task to update and verify the resolver list though.

Ping @comzeradd (Apologies if Github isn't the right place, PKGdb seems broken right now)
