### ISSUE TITLE
provide Android build via F-Droid

### ISSUE THREAD

**Issue by ilf** [jedisct1/dnscrypt-proxy#721]
Thanks for DNSCrypt, and the Android version.

Currently, https://dnscrypt.org/#dnscrypt-android sais, to install DNSCrypt for Android, one should download a ZIP file from https://download.dnscrypt.org/dnscrypt-proxy/ and install it via a custom recovery such as TWRP or CWM. This is only for advanced users, cumbersome and bad practice.

It would be much easier (and safer) to distribute DNSCrypt for Android via https://f-droid.org/

Would anyone feel up to the task of creating a build for the official F-Droid repository?

Thanks, and keep up the good work.

**Comment by licaon-kter** [comment]
This would need an actual app, not sure how you've envisioned this.

Say, my frankenstein Unbound+scripts one: https://github.com/smarek/android-unbound-dns/issues/18 ( I recommend build 12; nee comments there) ;)

**Comment by quantumpacket** [comment]
> - Dowload and install Universal Init.d from the **Google Play Store**. Follow the instructions until you see Your Kernel Has init.d Support.
> - The DNSCrypt proxy should be running at this point, but your device may still use the previous DNS settings. Download and install DNS Changer fron the **Google Play Store**. In order to actually use DNSCrypt, enter 127.0.0.1 as the primary DNS resolver. In order to stop using DNSCrypt, leave this field empty. 

The instructions also say to download two packages from the Google Play Store. Many people including myself do not install Google services on their custom flashed devices due to the security/privacy implications involved. Yes, I can manually do what those two apps would do, but advising people that they need Google services installed makes me uncomfortable. :stuck_out_tongue: 

If an official custom app cannot be made and offered via F-Droid, I would suggest at minimum change the documentation to add options on how to accomplish it without Google services.

@licaon-kter will your app be made available on F-Droid?

**Comment by licaon-kter** [comment]
You don't need Google services, just that those apps are hosted there.

That Init.d could be replaced with Termux:Boot (it will be on F-Droid soon)
That DNSchanger (needs root?) could be replaced by NetGuard (old version on F-Droid or get it from Github directly; root not needed)

My duct-tape-scripted app has too few users to matter, well see how things fare in the future.

**Comment by quantumpacket** [comment]
> You don't need Google services, just that those apps are hosted there.

Yeah, I was referring to the fact the docs instruct people to obtain the apps via Google Play. I'd recommend that the F-Droid alternatives be listed as well so people know there are other methods to obtain the same or equivalent dependencies.

> My duct-tape-scripted app has too few users to matter, well see how things fare in the future.

Well I'll be using it now, so that's +1 more. Thanks for making it. :smiley:
