### ISSUE TITLE
Stops working entirely after some time, have to reboot to fix it

### ISSUE THREAD

**Issue by anlutro** [jedisct1/dnscrypt-proxy#726]
I'm using dnscrypt-proxy 1.9.4, the stock version that comes with Debian Stretch/9.

After running it for some time, dnscrypt-proxy will simply stop responding to queries. "Some time" is usually somewhere between 24 and 72 hours, though with long periods of suspension inbetween. I'm not really seeing any particular patterns as to when it's happening, but it may be the case that it happens more often when running a program called streamlink, which does a lot of small HTTP requests.

I've ran `strace` on the process and all I see it doing is this:

```
epoll_wait(5, [], 32, 5000)             = 0
write(1, "Wed Aug 16 23:43:43 2017 [DEBUG] resolver timeout (UDP)\n", 56) = 56
epoll_wait(5, [], 32, 4997)             = 0
write(1, "Wed Aug 16 23:43:48 2017 [DEBUG] resolver timeout (UDP)\n", 56) = 56
epoll_wait(5, 
```

When making a DNS query, for example `host -v google.com 127.0.2.1`, this is all I see:

```
recvfrom(4, "\207<\1\0\0\1\0\0\0\0\0\0\6google\3com\0\0\1\0\1", 65508, 0, {sa_family=AF_INET, sin_port=htons(60485), sin_addr=inet_addr("127.0.0.1")}, [128->16]) = 28
sendto(8, "\3477d\0\326F\7 \342\213\24_\332\346P\301\3571\25\223o\277Z"..., 512, 0, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("185.121.177.177")}, 16) = 512
```

Nothing seems to be being read from the connection to 185.121.177.177. I am able to open a connection with telnet to that IP on port 443, `openssl s_client` also manges to connect.

The really weird thing is that restarting dnscrypt-proxy does not fix the issue in any way. The only way I can solve the problem seems to be rebooting the entire system.

This problem only started occuring somewhat recently (maybe the last month or so), but I can't say what package(s) I upgraded on the system that might have caused it.

I'm not sure how to debug this further. Suggestions?

**Comment by jedisct1** [comment]
Hi Andreas,

What plugins are you using?

Does it happen with other resolvers?

In order to rule out issues that are specific to this environment, can you uninstall everything and try these packages: https://github.com/jedisct1/dnscrypt-proxy-installer ?

**Comment by anlutro** [comment]
I'm not using any plugins.

I've tried setting ResolverName to both "fvz-anyone" and "dnscrypt.eu-nl", is there anything else I should try there?

Going to give the installer a shot. If I run the dnscrypt-proxy binary as root on my own, it seems to work fine, so there might be something going on with the way systemd sets up the socket.

**Comment by anlutro** [comment]
So this happened again, and was fixed immediately by restarting the socket service thingy: `systemctl restart dnscrypt-proxy.socket`

I guess it's a problem with either the Debian configuration or with systemd in Debian. Should this issue be closed, you think?

**Comment by Mannitou** [comment]
can you try to query your server in TCP?

using this command: 
``# **dig www.google.com @127.0.0.1 -p 153 +tcp**
``
``; <<>> DiG 9.10.3-P4-Ubuntu <<>> www.google.com @127.0.0.1 -p 153 +tcp
``;; global options: +cmd
``;; Got answer:
``;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13274
``;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1
``
``;; OPT PSEUDOSECTION:
``; EDNS: version: 0, flags:; udp: 4096
``;; QUESTION SECTION:
``;www.google.com.                        IN      A
``
``;; ANSWER SECTION:
``www.google.com.         38      IN      A       64.233.164.103
``www.google.com.         38      IN      A       64.233.164.147
``www.google.com.         38      IN      A       64.233.164.105
``www.google.com.         38      IN      A       64.233.164.106
``www.google.com.         38      IN      A       64.233.164.99
``www.google.com.         38      IN      A       64.233.164.104
``
``;; Query time: 618 msec
``;; SERVER: 127.0.0.1#153(127.0.0.1)
``;; WHEN: Mon Oct 09 20:04:41 CET 2017
``;; MSG SIZE  rcvd: 139

Because in my case in case reproduce the issue on my PC. After 72H dnscrypt-proxy refuses to answer to any udp request But in TCP it is still OK.
