### ISSUE TITLE
Add a CSV column to indicate filtering/censorship

### ISSUE THREAD

**Issue by DCPuser** [jedisct1/dnscrypt-proxy#745]
Currently the many Cryptostorm resolvers don't say anything about filtering/censoring in the "description" field but in fact they block queries for domains they believe are ad related or privacy unfriendly. Queries for blocked domains return a dummy SOA with NS "localhost" and address "0.0.0.0", and "no such domain" for A, MX, TXT, etc. Their block list includes some legit domains and that breaks things. That makes them unsuitable for general public use, but there's no way to know that just by looking at the list.

There may be others on the list that filter/censor with out indicating so in the description.

Add a column to the list that indicates whether the resolver does or does not filter or censor the DNS results. If a new column can't be added, require every resolver to clearly state in the "description" field whether they do or do not filter or censor results.

**Comment by licaon-kter** [comment]
Link to the blocked list?

**Comment by wulungnet** [comment]
you can "keep it simple", don't use them. There are many others to choose from the list, i.e. d0wn servers.
cryptostorm admin have every right to set their servers to current condition, I believe they had their own reason [policies] to do it.
to avoid / lessen the error yo could set it in round robin manually or using **dnsdist**.

**Comment by snorkasaurus** [comment]
I had a quick look and don't see any publicly available list of blocked/poisoned domains at the cryptostorm.is web site, or any indication that blocking/poisoning is being done.  Personally, as a DNSCrypt user, I would want to be clear on a number of my provider's policies, including blocking/poisoning.

While "not using them" might fix DCPuser's ability to access the unspecified "legit domains", it doesn't solve the problem of allowing DNSCrypt users to make an educated decision about which resolver[s] to use.  Cryptostorm makes up _more than a quarter of the currently listed public resolvers_ and users might interpret that as cryptostorm being

- More experienced and possibly more secure than other providers
- Financially more stable and less likely to go down temporarily or disappear for good
- Staffed by many people which could minimize recovery times in the event of failures
- Possibly affiliated with, or even responsible for DNSCrypt itself
- Geographically close since they host servers in more than a dozen countries

Regardless of whether or not any of these are true, they can make cryptostorm look like an attractive choice of provider.  However, if cryptostorm is actually blocking/poisoning, currently users do not seem to have a way to find out until they either run in to problems or start dig'ing at domains to test resolvability.  If I were a new user who ran in to problems because I unknowingly selected a provider who blocks some domains I might be inclined to stop using DNSCrypt and write it off as unreliable.  I think users would appreciate knowing up-front whether or not any blocking/poisoning is going on, and having that information in the resolver list would help users select a provider.

My three cents.

**Comment by jedisct1** [comment]
Instead of an additional field, providers that blocks ads or other coherent sets of domain should explain this in the description. If only because this will be immediately displayed in graphical front-ends.

Censorship is more tricky.

People submitting new entries are unlikely to say "hey, we do censorship". So, that information would come from users. But it's hard to confirm. There are many reasons why a domain would stop resolving. Having such information would be some kind of accusation, not always with tangible evidence.

A better solution could be to write some kind of public monitoring service, that resolves common domains (including ads) through all resolvers, and presents the result as a table.
That could be really useful, but I currently don't have time to work on that.
