### ISSUE TITLE
how can I disable "udp   0 0.0.0.0:39732" ?

### ISSUE THREAD

**Issue by larryduke** [jedisct1/dnscrypt-proxy#749]
thanks!

**Comment by jedisct1** [comment]
If you think this port is used by dnscrypt-proxy, you can restart it, and it will probably use a different port.

Most communications over the Internet use IP addresses. These are used to route messages to the intended computer. They also use "port" numbers, so that each computer can communicate with different services simultaneously.

When a message is sent to another computer, the sender chooses a local port number, and sends it to a known port number of the destination computer. When that destination computer responds, it does so by sending the response to the sender IP, and to the port number it choose. So that a DNS response doesn't go to your web browser or to your Skype client, but to whatever handles DNS on your computer. Even if the IP is the same.

"39732" is probably a port that was chosen by your computer to receive DNS responses. It doesn't have to be 39732. It's usually chosen randomly among ports that are not used by anything else.

Without a local port, you cannot receive responses from other computers. On a local network, there are ways to achieve this without using ports and even IP addresses, but on the Internet, this is required.
