### ISSUE TITLE
What should be client's behaviour when server restarts ? 

### ISSUE THREAD

**Issue by miteshjadia** [jedisct1/dnscrypt-proxy#762]
I was going through "dnscrypt-proxy" code which runs on client side and found that It tries to re-fetch certificate at the interval of one hour.

Below are the doubts.

What should be effective expiry duration of certificates generated on dnscrypt-server?
If it is less than an hour, should there be a logic on client side to re-fetch certificate before few seconds of current certificates expiry ?

What if server restarts at some point where client were already leased certificates ?
As of now dnscrypt-proxy (client) will still try to do communication using negotiated , which will fail at server. Should there be any certificate re-fetch event after few consecutive exceptions ?

**Comment by jedisct1** [comment]
Multiple certificates can be served simultaneously. Their time period overlap.

So that when a new certificate is created, the previous, whose expiration is after the start of the new one, is still served and valid.

In the docker image, certificates are valid for 24 hours, but a new one is issued every 12 hour.
