### ISSUE TITLE
Improvement suggestion: separate active servers list from code repo

### ISSUE THREAD

**Issue by neagix** [jedisct1/dnscrypt-proxy#768]
I see a lot of commits (most?) about servers that go up/down; wouldn't make more sense to have that list in a separate repo, and `dnscrypt-proxy` can either use a submodule or some other way to fetch it from there?

**Comment by jedisct1** [comment]
That's a good suggestion, but it would have some downsides:
- Some scripts fetch the list directly from github instead of the download site. They would be immediately broken.
- Submodules have been proven to be confusing. People forget `--recursive` even if you document it, don't know how to update them.

Splitting things into modules is great for large and complex projects, but that one is really small and simple. So I'm not sure submodules would be justified over the convenience of having everything at the same place.

Most recent commits are indeed about maintaining that list. Recent code such as the caching module and the new blocking module are great. But the core proxy itself is old code that I really want to rewrite from scratch. Especially to get rid of the patched libevent copy, and to ship a library that anyone can easily reuse in other apps.
Rewriting that code code shouldn't take more than a couple days, but I still need to find some motivation and a couple spare days to do it., unless someone wants to take over the project.

**Comment by neagix** [comment]
> Some scripts fetch the list directly from github instead of the download site. They would be immediately broken.

If you use a sub-directory (that then becomes the submodule), and a symlink, it should work with all curl/wget approaches.

> Submodules have been proven to be confusing. People forget --recursive even if you document it, don't know how to update them.

Well if you wan to build a C project, I expect that you can handle git submodules. That's of course my personal opinion. :) If instead non-C-developers need access to the files in the repo, one more reason to split it.

> Most recent commits are indeed about maintaining that list.

I was thinking that it's just going to be a constant flow, hence my suggestion here.

> But the core proxy itself is old code that should really be rewritten from scratch. Especially to get rid of the patched libevent copy, and to ship a library that anyone can easily reuse in other apps.
Rewriting that code code shouldn't take more than a couple days, but I still need to find some motivation and a couple spare days to do it, unless someone wants to take over the project.

I understand. These days I write mostly Go so I would be available only on that side (also to maintain it); it's not like I cannot do C, but I judge being a bit rusty compared for example to you. You could open the bounty on some open-source related website, or put an ad on the website, although in those ways the quality of contributions can vary wildly.

Feel free to close it if there are no plans to split the servers list somewhere else (actually even a gist would fit the bill here, and they can be used as submodules too).

**Comment by neagix** [comment]
I just tried what I mentioned (symlinks), and it does not work to issue a redirect. Nevermind, it would not be possible to support clients in a graceful way.

**Comment by neagix** [comment]
Closing in light of the new events (#769)
