### ISSUE TITLE
Feature request: option to use in regular DNS mode

### ISSUE THREAD

**Issue by Hygone** [jedisct1/dnscrypt-proxy#793]
I would like to request an optional mode that uses regular unencrypted unauthenticated DNS, whilst still retaining the other brilliant features of dnscrypt-proxy like filtering and cloaking. At the moment there is a lack of widespread support for DNSCrypt and DNS-over-HTTPS and there are various situations where it may be impossible or unwise to use the limited number of DNS servers that support these protocols. What I am thinking of would be similar to the existing fowarding rules but applied universally to all queries.

**Comment by Hygone** [comment]
Could this mode be handled by adding a new rule in forwarding rules? Forwarding rules already allows a subset of queries to go on regular DNS....

**Comment by jedisct1** [comment]
Forwarding may work indeed. You will lose the benefits of automatically retrieving updated lists of servers, and server selection, though.

But I'd rather encourage people to run more DNSCrypt and DoH servers than add an insecure mode to the proxy.

**Comment by Hygone** [comment]
I can understand that. It would be better to have more DNSCrypt and DoH servers, there is much benefit in them. But sending DNS requests only to particular servers can be a security and privacy risk too, even if the DNS requests are encrypted and authenticated. 

Maybe having the option for regular DNS could actually help the transition to the more secure protocols, because without support for regular DNS some people might simply not use DNSCrypt-proxy at all.

**Comment by publicarray** [comment]
Sorry but I disagree. We have a good number of encrypted severs to choose from. https://dnscrypt.info/map But I would always encourage people to add more. We have a number of smaller private servers but there are also ones from bigger organisations that can handle bigger loads e.g. cloudflare, quad9, powerdns etc. The question is who do you trust? And how reliable are they? And what location are they in? Or do you just use the fastest one automatically chosen?

I don’t see how sending dns queries to a single encrypted server is worse than sending them to unencrypted to your ISP or a number of unencrypted server of your choosing. I think by sending them to multiple servers you increase the risk that they are logged by at least one server. I guess if you assume all servers log than that could decrease the information by a single server. However I think most (private) server operators here are privacy conscious and I expect they won’t log but this is it hard to prove.

Sorry I don’t get the argument that supporting unencrypted DNS will lead to an increase of encrypted DNS usage.

You could use a dns server/cache like (dnsmasq or unbound) in front of dnscrypt-proxy to block or otherwise manipulate dns. It does require rewriting the rules though.
