### ISSUE TITLE
dnscrypt-proxy with random resolver name : sometimes hangs

### ISSUE THREAD

**Issue by deb75** [jedisct1/dnscrypt-proxy#800]
hello,

I use dnscrypt-procxy on debian stretch (official package) and I chose to randomize the resolver name.

But quite oftenly, dnscrypt seems to choose resolver names which are not functional.

Then I have to stop/start dnscrypt several time until I can get one working resolver name (this can be easily checked with "ping google.fr").

How can I prevent this ? The best way would be to make dnscrypt check each resolver name of the list before picking one up randomly.

Regards

**Comment by jedisct1** [comment]
Your resolver list is probably out of date. The code ships with a `dnscrypt-update-resolvers.sh` scripts that updates the list. I don't know if Debian install it and calls it automatically.

Otherwise the always up-to-date list can be downloaded here: https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-resolvers.csv

**Comment by deb75** [comment]
It seems indeed debian does not ship this script with its package.

**Comment by snorkasaurus** [comment]
You may also want to look through the resolver list and choose one that best suits you based on geographic location, logging, DNSSEC, IPv6, censorship/blocking, etc.  If you wish to use multiple resolvers for fault tolerance you can easily run dnsmasq as a stub resolver with multiple dnscrypt-proxy instances connected to different servers.

Either way, it is a good idea to update your resolver list with some regularity.  Sometimes it is weeks between changes and sometimes only a day or two.

**Comment by deb75** [comment]
Hi,

Thanks for your answeer, I would be interested with the multiple resolvers solution. But I do not see what is a stub resolver and how to configure dnsmasq ?

I retrieved the `dnscrypt-update-resolvers.sh` script, I saw inside the command :
`curl -L https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-resolvers.csv`

Trouble is that if the dns resolver is unreachable, this command will not work !?

So I would suggest to replace "download.dnscrypt.org" directly with its IP address : 37.59.238.213. Nevertheless, is this IP address static or dynamic ? If dynamic how long does it take to change ?

Regards

**Comment by snorkasaurus** [comment]
This might be a bit outside the scope of DNSCrypt support, but I guess other folks may have similar questions.  A recursive resolver is one that starts with the [root servers](https://en.wikipedia.org/wiki/Root_name_server) and works its way down to resolve queries.  A [stub resolver](https://en.wikipedia.org/wiki/Domain_Name_System_Security_Extensions#Stub_resolvers) is one that asks an upstream (probably recursive) resolver for answers to queries.  A stub resolver can be used on your local PC only, or on a LAN to provide DNS services for a bunch of devices.  A stub resolver usually uses caching to provide faster responses for frequently requested names (like if you clicked on both those Wikipedia links above).

[dnsmasq](http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html) is a stub resolver that can use multiple upstream recursive resolvers.  If you setup multiple dnscrypt-proxy connections like this:

  * dnscrypt-proxy -R some-dnscrypt-server -a 127.0.0.1:1153
  * dnscrypt-proxy -R another-dnscrypt-server -a 127.0.0.1:1154
  * dnscrypt-proxy -R theother-dnscrypt-server -a 127.0.0.1:1155

then you can tell dnsmasq to use all of them by setting up your /etc/dnsmasq.conf with:

    server=127.0.0.1#1153
    server=127.0.0.1#1154
    server=127.0.0.1#1155

Note the use of "#" rather than ":" to separate the IP address from the port.

There really is a lot more to dnsmasq, so don't just paste that in and pray it works, you'll want to read through the well-commented dnsmasq.conf file to understand how it works.

As for the curl command, it is probably easiest to temporarily change your DNS settings to a regular non-encrypted DNS server just so you can pickup the updated resolver list.  It will just be easier than trying to download the list without functional DNS services.

My three cents.

**Comment by dtcyganok** [comment]
@jedisct1 
I would like to emphasize one important detail. Some resolvers (dnscrypt.eu-nl, ipredator and maybe others) from the actual csv file are sometimes unavailable for several hours.
